### ISSUE TITLE
Guidance on integrating with HttpClientFactory

### ISSUE THREAD

**Issue by stijnherreman** [simpleinjector/SimpleInjector#654] opened 2019-01-14 14:45 UTC
Currently I register some dependencies like this:

```csharp
var fooHttpClient = new HttpClient();
fooHttpClient.BaseAddress = new Uri($"{this.appSettings.FooUri}/");
container.Register<Foo.IClient>(() => new Foo.Client(fooHttpClient), Lifestyle.Scoped);
```
I want to move to [HttpClientFactory](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests).
* I can register a Named Client with `IServiceCollection.AddHttpClient(...)` but then I'd have to resolve the named client when configuring the SimpleInjector container. (I haven't tried yet if this is actually possible.)
* I can register a Typed Client with `IServiceCollection.AddHttpClient(...)` but then SimpleInjector is not involved at all.

Do you have any guidance on this subject?

**Comment by dotnetjunkie** [comment] 2019-01-14 15:45
Moving to the new HttpClientFactory model is good, considering all the pitfalls that exist with the problematic design of `HttpClient`.

Unfortunately, the injection of typed clients (i.e. using `AddHttpClient`) is very tightly coupled with the built-in container, and still quite [error prone](https://github.com/aspnet/Extensions/issues/924).

Instead, I'd advise injecting `IHttpClientFactory` into your `HttpClient`'s consumers and use its `CreateClient` method to resolve the required client, much like is described [here](https://docs.microsoft.com/nl-nl/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#basic-usage). 

Here's an example:

``` c#
public sealed class HttpGithubClient : IGithubClient
{
    private readonly IHttpClientFactory clientFactory;
    private readonly HttpGithubClientSettings settings;
    
    public HttpGithubClient(
        IHttpClientFactory clientFactory,
        HttpGithubClientSettings settings)
    {
        this.clientFactory = clientFactory;
        this.settings = settings;
    }

    public async Task<GitHubBranch[]> GetBranches()
    {
        var request = new HttpRequestMessage(
            HttpMethod.Get,
            this.settings.GithubRootUrl + "/repos/aspnet/docs/branches");
        request.Headers.Add("Accept", "application/vnd.github.v3+json");
        request.Headers.Add("User-Agent", this.settings.UserAgent);

        using (var client = this.clientFactory.CreateClient())
        {
            var response = await client.SendAsync(request);

            if (response.IsSuccessStatusCode)
            {
                return await response.Content
                    .ReadAsAsync<IEnumerable<GitHubBranch>>()
                    .ToArray();
            }
            else
            {
                throw new HttpException("...");
            }
        }
    }
}
```

This example is an altered version of the one in the MS doc, with the following changes:

* The component is stateless, prevent your components from having state whenever possible
* As an example, the component uses a `HttpGithubClientSettings` configuration object. This allows allows required configuration values to be supplied by the Composition Root, if required. The configuration object is specific to this particular component.
* The created `HttpClient` is now wrapped in a `using` statement. `HttpClient` instances should still be disposed.
* The method throws an exception on failure, instead of returning error codes using the boolean property (really bad idea).

**Comment by stijnherreman** [comment] 2019-01-14 15:52
Thank you for the info. I'll have a look and see what's possible, these clients are generated by https://github.com/RSuter/NSwag but there's a lot of configuration possible.

**Comment by rexcfnghk** [comment] 2019-01-15 06:08
> Moving to the new HttpClientFactory model is good, considering all the pitfalls that exist with the problematic design of `HttpClient`.
> 
> Unfortunately, the injection of typed clients (i.e. using `AddHttpClient`) is very tightly coupled with the built-in container, and still quite [error prone](https://github.com/aspnet/Extensions/issues/924).
> 
> Instead, I'd advise injecting `IHttpClientFactory` into your `HttpClient`'s consumers and use its `CreateClient` method to resolve the required client, much like is described [here](https://docs.microsoft.com/nl-nl/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#basic-usage).
> 
> Here's an example:
> 
> ```cs
> public sealed class HttpGithubClient : IGithubClient
> {
>     private readonly IHttpClientFactory clientFactory;
>     private readonly HttpGithubClientSettings settings;
>     
>     public HttpGithubClient(
>         IHttpClientFactory clientFactory,
>         HttpGithubClientSettings settings)
>     {
>         this.clientFactory = clientFactory;
>         this.settings = settings;
>     }
> 
>     public async Task<GitHubBranch[]> GetBranches()
>     {
>         var request = new HttpRequestMessage(
>             HttpMethod.Get,
>             this.settings.GithubRootUrl + "/repos/aspnet/docs/branches");
>         request.Headers.Add("Accept", "application/vnd.github.v3+json");
>         request.Headers.Add("User-Agent", this.settings.UserAgent);
> 
>         using (var client = this.clientFactory.CreateClient())
>         {
>             var response = await client.SendAsync(request);
> 
>             if (response.IsSuccessStatusCode)
>             {
>                 return await response.Content
>                     .ReadAsAsync<IEnumerable<GitHubBranch>>()
>                     .ToArray();
>             }
>             else
>             {
>                 throw new HttpException("...");
>             }
>         }
>     }
> }
> ```
> 
> This example is an altered version of the one in the MS doc, with the following changes:
> 
> * The component is stateless, prevent your components from having state whenever possible
> * As an example, the component uses a `HttpGithubClientSettings` configuration object. This allows allows required configuration values to be supplied by the Composition Root, if required. The configuration object is specific to this particular component.
> * The created `HttpClient` is now wrapped in a `using` statement. `HttpClient` instances should still be disposed.
> * The method throws an exception on failure, instead of returning error codes using the boolean property (really bad idea).

Shouldn't `HttpGitHubClient` avoid depending on a framework abstraction and instead define its own `IHttpClientManager` interface instead?

**Comment by rexcfnghk** [comment] 2019-01-15 07:49
> > Shouldn't HttpGitHubClient avoid depending on a framework abstraction and instead define its own IHttpClientManager interface instead?
> 
> Not when you consider the HttpGitHubClient to be the adapter implementation. The IGitHubClient is in that case the application-specific abstraction.

I see. That makes sense! Thanks!

**Comment by ralphhendriks** [comment] 2019-01-28 13:03
@dotnetjunkie I am puzzled by this part of your answer

> The created `HttpClient` is now wrapped in a `using` statement. `HttpClient` instances should still be disposed.

I think that last statement is an incorrect advice. The [Mircrosoft docs](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net-core) quite clearly describe what is wrong with disposing `HttpClient`:

> As a first issue, while this class is disposable, using it with the `using` statement is not the best choice because even when you dispose `HttpClient` object, the underlying socket is not immediately released and can cause a serious issue named ‘sockets exhaustion’.

Wouldn't explicitly disposing the `HttpClient` generated by the `clientFactory` the lifetime management solution offered by `IHttpClientFactory`?

**Comment by ralphhendriks** [comment] 2019-01-29 10:45
@dotnetjunkie that makes sense. Thank you for the detailed explanation.

I think this is an issue many developers will struggle with. Would it be an idea to add some hints to the docs? If you like I could do a first attempt, but maybe this is in better hands with someone more intimately familiar with the subject matter 😊

**Comment by dotnetjunkie** [comment] 2019-01-29 11:14
Hi @ralphhendriks,

It will probably be just enough to add a link to this discussion from [Other Technologies section](https://simpleinjector.readthedocs.io/en/latest/integration.html#other-technologies) of the integration page. I just added that link.

**Comment by ziongh** [comment] 2019-02-11 00:21
@dotnetjunkie your explanation about stateless components make total sense.

So we would register the `IHttpClientFactory` as a Singleton. However the implementation that is used by microsoft `services.AddHttpClient()` is internal (`DefaultHttpClientFactory`) and depends on `IServiceProvider` and other internal classes.

You would recomend using Cross-Wiring for this interface or developing our own implementation?

Just to be shure, if I choose to develop my own implementation, I would need to track the lifetime of `HttpMessageHandler` and some race conditions.

And considering the use o **Polly** for a resilient `HttpClient`, you would recomend adding this logic on the implementation of IHttpClientFactory.CreateHttpClient?

**Comment by dotnetjunkie** [comment] 2019-02-11 07:28
I recommend using the `DefaultHttpClientFactory` and let it be injected using Simple Injector's auto-wiring facilities, exactly because it is an internal and complex component. Do not implement your own. That would be unproductive.

I'm unfamiliar with Polly and how it compares to the new IHttpClientFactory, so I can't comment on that.

**Comment by voroninp** [comment] 2019-02-20 08:38
@dotnetjunkie Do I understand correctly that typed clients are not supported by SimpleInjector?

I add typed client `services.AddHttpClient<EmailClient>()`, but get an exception:

> System.InvalidOperationException
> ActivationException: The constructor of type EmailClient contains the parameter with name 'httpClient' and type HttpClient that is not registered. Please ensure HttpClient is registered, or change the constructor of ConnectEmailClient.

**Comment by dotnetjunkie** [comment] 2019-02-20 19:31
> @dotnetjunkie Do I understand correctly that typed clients are not supported by SimpleInjector?

Oh, you can use typed clients if you really, really want to, but I advise against it as described above.

But if you want to use typed clients, such as your `EmailClient` its just a matter of (auto) cross-wiring that `EmailClient` in Simple Injector. And in case `EmailClient` contains dependencies that need to be resolved from Simple Injector, you should cross-wire them in MS.DI.

Example with `EmailClient` without extra dependencies:

``` c#
services.AddHttpClient<EmailClient>();

// only required when not using auto-cross-wiring
container.CrossWire<EmailClient>();
```

Example with `EmailClient` with extra `IDep` dependency:

``` c#
services.AddHttpClient<EmailClient>();

// cross-wire back to Simple Injector
services.AddScoped<IDep>(c =>
    container.GetInstance<IDep>());

container.Register<IDep, DepImpl>();
// only required when not using auto-cross-wiring
container.CrossWire<EmailClient>();
```

Et viola! That isn't that difficult. But again, due to the many problems and weaknesses with those typed clients, my advice is to inject a factory directly into your client.

**Comment by voroninp** [comment] 2019-02-20 19:47
@dotnetjunkie I tried factory, but it returned just arbitrary HttpClient, not configured one.

**Comment by dotnetjunkie** [comment] 2019-02-20 19:57
@voroninp keep on trying. Do bote that in my example, all configuration is done inside the client (using the request message), although I think you can request a named httpclient as well from the factory. Unfortunately, I'm unable to dive into this as I'm AFK.

**Comment by AlanMcBee** [comment] 2019-09-01 20:34
I'm not sure how recently this section was added to the docs, but there is some guidance around whether to dispose the `HttpClient `produced by the factory: https://docs.microsoft.com/aspnet/core/fundamentals/http-requests#httpclient-and-lifetime-management

Specifically, this paragraph:

> Disposal of the client isn't required. Disposal cancels outgoing requests and guarantees the given `HttpClient `instance can't be used after calling `Dispose`. `IHttpClientFactory `tracks and disposes resources used by `HttpClient `instances. The `HttpClient `instances can generally be treated as .NET objects not requiring disposal.

Thoughts?

**Comment by dotnetjunkie** [comment] 2019-09-02 08:19
@AlanMcBee,

> Disposal of the client isn't required.

It's common sense to deterministically dispose disposable implementations. Even though it isn't *required*, it will not hurt either. My advice is, therefore, to still dispose those `IHttpClient` instances.

**Closed** 2019-09-02 08:19 UTC
Labels: question

**Comment by kmute90** [comment] 2020-05-04 11:05
how are we supposed to inject `DefaultHttpClientFactory` ? It is internal, i cannot access unless using reflection ?

**Comment by dotnetjunkie** [comment] 2020-05-04 15:04
> how are we supposed to inject DefaultHttpClientFactory ? It is internal, i cannot access unless using reflection ?

As stated in the discussion and [the code samples](https://github.com/simpleinjector/SimpleInjector/issues/654#issuecomment-454051502) above, you should let your (Simple Injector-resolved) components depend on `IHttpClientFactory`). Simple Injector will automatically pull the `IHttpClientFactory` implementation from .NET Core's configuration system.

**Comment by kmute90** [comment] 2020-05-04 15:19
Thanks for the response, but I'd like to use it in a .net48 environment, is it possible in the scenario?

**Comment by dotnetjunkie** [comment] 2020-05-04 15:21
Hi @kmute90, this is the time that you create a new issue with your question, where you state what you have tried, and where you're stuck. When you do, please follow the issue template by providing all the relevant details.

**Comment by Leftyx** [comment] 2020-09-23 09:24
> 
> 
> Moving to the new `HttpClientFactory` model is a good idea, considering all the pitfalls that exist with the problematic design of `HttpClient`.
> 
> Unfortunately, the injection of typed clients (i.e. using `AddHttpClient`) is very tightly coupled with the built-in container, and still quite [error prone](https://github.com/aspnet/Extensions/issues/924).
> 
> Instead, I'd advise injecting `IHttpClientFactory` into your `HttpClient`'s consumers and use its `CreateClient` method to resolve the required client, much like is described [here](https://docs.microsoft.com/nl-nl/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#basic-usage).
> 
> Here's an example:
> 
> ```cs
> public sealed class HttpGithubClient : IGithubClient
> {
>     private readonly IHttpClientFactory clientFactory;
>     private readonly HttpGithubClientSettings settings;
>     
>     public HttpGithubClient(
>         IHttpClientFactory clientFactory,
>         HttpGithubClientSettings settings)
>     {
>         this.clientFactory = clientFactory;
>         this.settings = settings;
>     }
> 
>     public async Task<GitHubBranch[]> GetBranches()
>     {
>         var request = new HttpRequestMessage(
>             HttpMethod.Get,
>             this.settings.GithubRootUrl + "/repos/aspnet/docs/branches");
>         request.Headers.Add("Accept", "application/vnd.github.v3+json");
>         request.Headers.Add("User-Agent", this.settings.UserAgent);
> 
>         using (var client = this.clientFactory.CreateClient())
>         {
>             var response = await client.SendAsync(request);
> 
>             if (response.IsSuccessStatusCode)
>             {
>                 return await response.Content
>                     .ReadAsAsync<IEnumerable<GitHubBranch>>()
>                     .ToArray();
>             }
>             else
>             {
>                 throw new HttpException("...");
>             }
>         }
>     }
> }
> ```
> 
> This example is an altered version of the one in the MS doc, with the following changes:
> 
>     * The component is stateless, prevent your components from having state whenever possible
> 
>     * As an example, the component uses a `HttpGithubClientSettings` configuration object. This allows required configuration values to be supplied by the Composition Root, if required. The configuration object is specific to this particular component.
> 
>     * The created `HttpClient` is now wrapped in a `using` statement. `HttpClient` instances should still be disposed.
> 
>     * The method throws an exception on failure, instead of returning error codes using the boolean property (really bad idea).

Hi Steven,

is there any specific reason why you're not disposing `HttpRequestMessage` ?

Thanks

**Comment by dotnetjunkie** [comment] 2020-09-23 09:33
@Leftyx,

I'm not the right person to ask. The code sample is an adapted version of [that from the Microsoft documentation](https://docs.microsoft.com/nl-nl/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#basic-usage). In that example it isn't disposed either. It's best to ask Microsoft. But [this SO q/a](https://stackoverflow.com/questions/38083206/not-calling-dispose-on-httprequestmessage-and-httpresponsemessage-in-asp-net-cor) might help.

**Comment by Leftyx** [comment] 2020-09-23 09:47
@dotnetjunkie, thanks. 
It seems that only the request [content](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpRequestMessage.cs#L214) is disposed so I guess it's fine to dispose.

**Comment by lennartb-** [comment] 2021-09-22 12:18
> > how are we supposed to inject DefaultHttpClientFactory ? It is internal, i cannot access unless using reflection ?
> 
> As stated in the discussion and [the code samples](https://github.com/simpleinjector/SimpleInjector/issues/654#issuecomment-454051502) above, you should let your (Simple Injector-resolved) components depend on `IHttpClientFactory`). Simple Injector will automatically pull the `IHttpClientFactory` implementation from .NET Core's configuration system.

I'm not sure if I understand you correctly, but I tried registering it with `container.RegisterSingleton<IHttpClientFactory>();` which results in an ArgumentException ("The given type IHttpClientFactory is not a concrete type. Please use one of the other overloads to register this type"). We're using .NET 5. Does this only work on .NET Core (< 5), or am I missing something?

**Comment by rexcfnghk** [comment] 2021-09-22 12:43
> > > how are we supposed to inject DefaultHttpClientFactory ? It is internal, i cannot access unless using reflection ?
> > 
> > 
> > As stated in the discussion and [the code samples](https://github.com/simpleinjector/SimpleInjector/issues/654#issuecomment-454051502) above, you should let your (Simple Injector-resolved) components depend on `IHttpClientFactory`). Simple Injector will automatically pull the `IHttpClientFactory` implementation from .NET Core's configuration system.
> 
> I'm not sure if I understand you correctly, but I tried registering it with `container.RegisterSingleton<IHttpClientFactory>();` which results in an ArgumentException ("The given type IHttpClientFactory is not a concrete type. Please use one of the other overloads to register this type"). We're using .NET 5. Does this only work on .NET Core (< 5), or am I missing something?

I think you misunderstood. Let's say you have a `MyHttpClient` class like:

```c#
public class MyHttpClient
{
    private readonly IHttpClientFactory _httpClientFactory;

    public MyHttpClient(IHttpClientFactory httpClientFactory)
        => _httpClientFactory = httpClientFactory;
}
```

You should register `HttpClient`s through `IServiceCollection` via `services.AddHttpClient()`. You do not need additional registrations for Simple Injector if you are using auto cross-wiring. Simple Injector will automatically resolve `IHttpClientFactory` through Microsoft DI.

**Comment by lennartb-** [comment] 2021-09-22 12:57
Ah, I don't have a Microsoft DI container in our case, so there was nothing to cross-wire. Doing it the framework way works though.

**Comment by tmp1k** [comment] 2022-03-25 15:08
oh i think I'm missing a using statement for the httpClient instance result of factory create. could that be my oversight. i think if the count stays at 1 that means previous instances are getting cleaned and perhaps the last used one is still holding but that should be OK.

**Comment by dotnetjunkie** [comment] 2022-03-25 15:28
Hi @tmp1k, I'm not sure whether there is a question in your comment, or it's just an observation. If you have a question, would you mind rephrasing it?

**Comment by tmp1k** [comment] 2022-03-25 16:08
@dotnetjunkie oops my bad. that previous comment was intended for a different thread regarding default http client factory cleanup cycle debug logs on cleanup cycle ending the remaining count keep increasing after following the paradigm guidelines described in the thread. I'm wondering why the remaining count keeps increasing ` Ending HttpMessageHandler cleanup cycle after 0.0029ms - processed: 0 items - remaining: 1 items`

**Comment by pseabury** [comment] 2022-08-05 16:45
In Azure Functions (v3 on NetCore3.1) using SimpleInjector 5.3, I've followed the guidance here using IHttpClientFactory instead of a typed client that depends on a MS DI-constructed HttpClient, but SimpleInjector can't resolve the IHttpClientFactory either.

```C#
public class FooClient
{
    private IHttpClientFactory _clientFactory;
    private FooClientConfig _config;        
    public FooClient(IHttpClientFactory clientFactory, FooClientConfig config) 
    {
        _clientFactory = clientFactory;
        _config = config;           
    }
}
```

```C#
public class Startup : FunctionsStartup
{  
    public void ConfigureServices(IServiceCollection services)
    {   
        services.AddHttpClient();
    
        var container = new Container();
        container.RegisterInstance<FooClientConfig>(new FooClientConfig() { ApiKey = Configuration.GetValue<string>("FooApiKey") });
        container.Register<FooClient>();

        services.AddSimpleInjector(container);
    }
}
```

```C#
public class FooCommandHandler 
{
    private readonly FooClient _fooClient;
    
    public FooCommandHandler (FooClient client) 
    {
      _fooClient = fooClient;
    }
}
```
I then use the container to activate a Command/Query mediator but the container can't find an IHttpClientFactory to use for the FooClient.  

> SimpleInjector.ActivationException: 'The configuration is invalid. Creating the instance for type FooClient failed. The constructor of type FooClient contains the parameter with name 'clientFactory' and type IHttpClientFactory, but IHttpClientFactory is not registered. For IHttpClientFactory to be resolved, it must be registered in the container. Verification was triggered because Container.Options.EnableAutoVerification was enabled. To prevent the container from being verified on first resolve, set Container.Options.EnableAutoVerification to false.'

I guess my question is, where am I supposed to setup the Auto-cross-wiring for simpleinjector?  I thought the call to `services.AddSimpleInjector(container);` would make the MS DI registered IHttpClientFactory available to the container and thus to the registrations therein.

Crossposted on [SO here](https://stackoverflow.com/questions/73252962/ihttpclientfactory-and-simpleinjector-in-azurefunctions) since this question has been closed.

**Comment by tsahi** [comment] 2023-11-19 11:40
> You should register `HttpClient`s through `IServiceCollection` via `services.AddHttpClient()`. You do not need additional registrations for Simple Injector if you are using auto cross-wiring. Simple Injector will automatically resolve `IHttpClientFactory` through Microsoft DI.

But what do you do in .NET Framework, where you don't normally use `IServiceCollection`? I found [this guide](https://www.mytechramblings.com/posts/dotnet-httpclient-basic-usage-scenarios/) (using Autofac as an example). Is this a good way to use `IHttpClientFactory` in .NET Framework with a third-party DI containter such as Simple Injector?

**Comment by dotnetjunkie** [comment] 2023-11-19 21:56
> But what do you do in .NET Framework, where you don't normally use IServiceCollection?

You start using the `IServiceCollection`. The new `HttpClient` library is tightly coupled to the `IServiceCollection` anyway. The integration guide [shows](https://docs.simpleinjector.org/en/latest/servicecollectionintegration.html) an example of how to do this. Basically:

``` c#
public static void Main()
{
    var container = new Container();

    new ServiceCollection()
        .AddHttpClient()
        .AddSimpleInjector(container)
        .BuildServiceProvider(validateScopes: true)
        .UseSimpleInjector(container);

    // Register application components.
    container.Register<IService, SomeServiceDependingOnHttpClientFactory>();

    // Always verify the container
    container.Verify();

    // Run application code
    using (AsyncScopedLifestyle.BeginScope(container))
    {
        var service = container.GetInstance<IService>();
        service.DoAwesomeStuff();
    }
}
```

**Comment by waiwaing** [comment] 2025-04-29 10:44
What is the recommendation if we want to modify the HttpClientHandler? For example, our use case is that we want to set `AllowAutoRedirect = false` for some of our HTTP clients. As I understand it:

* the [recommended route](https://github.com/simpleinjector/SimpleInjector/issues/654#issuecomment-462237772) is to have SimpleInjector wire the DefaultHttpClientFactory
  * the consequence though is that you can't provide a custom `IHttpClientHandler`
* typed clients, which do allow this, aren't recommended
  *  in any case, they require explicit cross-wiring using `AddScoped` back to SimpleInjector of every dependency referenced in the constructor of the typed client which is annoying at best

**Comment by dotnetjunkie** [comment] 2025-04-29 13:04
@waiwaing, I'm not that familiar with that part of the HttpClientHandler's API, but if I'm not mistaken, you can configure your HttpClient with a name (as you see in the MS docs) and `and `AllowAutoRedirect` overwrite, while calling the `IHttpClientFactory` while passing on the exact name 

``` c#
builder.AddHttpClient("MySpecialClient")
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
            {
                AllowAutoRedirect = false,
                AutomaticDecompression = DecompressionMethods.Deflate | 
                DecompressionMethods.GZip
            }); 
```

And in your component, you do:

``` c#
public class MyComponent(IHttpClientFactory factory)
{
    public void DoSomething()
    {
        using client = factory.CreateClient("MySpecialClient");
        // use client
    }
}
```

I hope this helps
