### ISSUE TITLE
Context not injected correctly in asp.net 5

### ISSUE THREAD

**Issue by Gillardo** [simpleinjector/SimpleInjector#168] opened 2016-01-13 15:19 UTC
I am in the process of writing an api using asp.net 5, and i got so far and my context was being injected.  I have striped and gutted the code to a bare minimum and it seems to be a problem with SimpleInjector (or the way i have done something).

If i commented out the following 2 lines (think you can do the first one only) and use asp.net DI, then it works.  

The lines to comment out are on the startup.cs file at line 67

```services.AddScoped<IControllerActivator>(e => new SimpleInjectorControllerActivator(_container));```

And line 81
```app.UseSimpleInjector(_container, _configuration);```

If you load up the project, it will display a simple page, with a page.  If you are using asp.net DI, you will get a response of "Hi bob".

Once you switch to using SimpleInjector, you get an error message saying 

**Cannot access a disposed object.
Object name: 'ApplicationDbContext'.**

Now this maybe something to do with it, but not sure.  But if i also comment out the 31 on AppBuilderExtensions.cs file, which reads ```container.CrossWire<ApplicationDbContext>(app);```, then upon starting the application, i get a SimpleInjector Verify error, saying

**-[Disposable Transient Component] ApplicationDbContext is registered as transient, but implements IDisposable.**

To get round this, i added the line that you just commented out.

What is wrong here?  I cannot seem to work it out.  Really appreciate any help.

Please find the sample project attached here

[SimpleInjectorContextTest.zip](https://github.com/simpleinjector/SimpleInjector/files/89183/SimpleInjectorContextTest.zip)

**Comment by qujck** [comment] 2016-01-13 15:30
Which version of SI are you using?

**Comment by Gillardo** [comment] 2016-01-13 15:49
dependencies are

        "SimpleInjector": "3.1.2",
        "SimpleInjector.Integration.AspNet": "3.1.2-beta4",

**Comment by Gillardo** [comment] 2016-01-13 15:49
I have attached project as well

**Comment by qujck** [comment] 2016-01-13 16:28
Ok, I cannot get the code to run on my PC at work, I will try at home later.

My first suspicion is that `AddDbContext` is registering `ApplicationDbContext` with a lifetime (as it should) but `CrossWire` resolves without first resolving any instance of a scope object (`IServiceScope`) and as there is no held reference to the instance of `IServiceScope` that `ApplicationDbContext` is resolved from they are both immediately disposed.

DISCLAIMER: I made that up foom reading the code, I could very easily be wrong :-/

**Comment by Gillardo** [comment] 2016-01-13 16:35
The code requires you to use rc2 of asp.net5, so you will need to run ```dnvm upgrade -u ```

**Comment by dotnetjunkie** [comment] 2016-01-13 17:15
I'm unable to take a look at the source code, but what is this `UseSimpleInjector` method you are callig? That's not something from the integration package.

I also see you're not following the integration guide; it dictates to register the IControllerActivator as singleton.

Furthermore, could it be you are using an old version of the integration package? Beta4 actually suppresses the IDisposable transient diagnostic warning. You shouldn't get this error at all.

Besides, it seems weird that you register your application's DbContext in ASP.NET and crosswire it in Simple Injector. That DbContext seems an application component to me, not some framework component.

**Comment by Gillardo** [comment] 2016-01-13 19:22
```UseSimpleInjector``` is just an extension method i created so i could keep all my container code in without having it in the startup.cs file.

I have tried singleton with icontrolleractivator but didnt make a difference but that is my mistake and i will change that.

I believe i am using the correct version as beta4 is stated in my project.json file.

How can i ise DbContext without registering it with Asp.net? In EF6 u could simply pass in a connectionstring but EF7 doesnt seem to allow u to do this? I dont have any experience with EF7 and all examples seem to use what i have. Happy to do it dofferent way.  In my EF6 code i would of done ```container.Register(() => new DbContext("connectionString"), Lifestyle.Scoped)```

**Comment by TheBigRic** [comment] 2016-01-13 20:46
I'm unable to help you with all the Asp.Net stuff, but configuring a connectionstring for a DbContext in EF7 seems doable, although different as in EF6.

It's quite extensively documented on the asp.Net\Entityframework repo. See [Configuring a DbContext](https://github.com/aspnet/EntityFramework/wiki/Configuring-a-DbContext)

**Comment by qujck** [comment] 2016-01-13 22:32
I've not made a lot of progress but I have found something odd: if I comment out the module level variable `private Container _container` and adjust the code until it is compiling (by effectively removing Simple Injector) the code still fails with the same error.

**Comment by Gillardo** [comment] 2016-01-13 23:03
I have looked at the EF7 link you sent me, but a DbContext doesnt have a base constructor that accepts anything?  Not sure why you guys cant compile the code....  It works fine if you dont use SimpleInjector on my machine, just not with

**Comment by Gillardo** [comment] 2016-01-13 23:21
Guys to confirm, commenting out the 2 lines to do with SI allows it all to work fine... Something is definitely amiss

**Comment by qujck** [comment] 2016-01-13 23:23
I get the error

> 200: Cannot access a disposed object.
Object name: 'ApplicationDbContext'.

when I click *Call Auth Method* on the web page that is displayed when run this code:

```csharp
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Data.Entity;
using System.Linq;
using SimpleInjectorContextTest.Web.Models;

namespace SimpleInjectorContextTest.Web
{
    public class Startup
    {
        // rc2
        public static void Main(string[] args)
        {
            var application = new WebApplicationBuilder()
                .UseConfiguration(WebApplicationConfiguration.GetDefault(args))
                .UseStartup<Startup>()
                .Build();

            application.Run();
        }

        private IConfiguration _configuration;

        public Startup(IHostingEnvironment env)
        {
            // configuration is in the folder above the wwwroot
            var builder = new ConfigurationBuilder();

            builder
               .AddJsonFile("config.json")
               .AddEnvironmentVariables();

            _configuration = builder.Build();
        }

        // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            // Add MVC services to the services container.
            services.AddMvc();

            services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(_configuration["Data:DefaultConnection:ConnectionString"]));
            
            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddOpenIddict(); // Add the OpenIddict services after registering the Identity services.
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            // logger support
            loggerFactory
                .AddConsole(_configuration.GetSection("Logging"))
                .AddDebug();

            // Handle errors when in development mode
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }

            // use jwt bearer authentication
            app.UseJwtBearerAuthentication(options =>
            {
                options.AutomaticAuthenticate = true;
                options.AutomaticChallenge = true;
                options.RequireHttpsMetadata = false;
                options.Audience = "http://localhost:5000/";
                options.Authority = "http://localhost:5000/";
            });

            // Add all the external providers you need before registering OpenIddict:
            //app.UseFacebookAuthentication();

            app.UseOpenIddict();

            // Enable all static file middleware
            app.UseStaticFiles();

            // Enable Mvc for view controller, and 
            // default all routes to the Home controller
            app.UseMvc(options =>
            {
                options.MapRoute(
                    name: "default",
                    template: "{*url}",
                    defaults: new { controller = "Home", action = "Index" });
            });

            using (var context = app.ApplicationServices.GetRequiredService<ApplicationDbContext>())
            {
                context.Database.EnsureCreated();

                if (!context.Applications.Any())
                {
                    context.Applications.Add(new OpenIddict.Models.Application
                    {
                        Id = "myClient",
                        DisplayName = "My client application",
                        RedirectUri = "http://localhost:5000/signin-oidc",
                        LogoutRedirectUri = "http://localhost:5000/",
                        Secret = CryptoHelper.Crypto.HashPassword("secret_secret_secret"),
                        Type = OpenIddict.OpenIddictConstants.ApplicationTypes.Confidential
                    });

                    context.SaveChanges();
                }
            }
        }
    }
}
```

**Comment by Gillardo** [comment] 2016-01-13 23:30
Stupid question, have you rebuilt?  Are you running using command ```dnx web``` or IIS Express?  I have copied and pasted your startup.cs and i get no error....

**Comment by qujck** [comment] 2016-01-13 23:31
IIS Express

**Comment by Gillardo** [comment] 2016-01-13 23:32
Works fine for me using dnx and IISExpress.... What version of dnvm have you got installed?  I am using 1.0.0-rc2-16357 x64

**Comment by qujck** [comment] 2016-01-13 23:37
I've 16 different runtimes in my profile, what tells me which one it is using?

**Comment by Gillardo** [comment] 2016-01-13 23:40
Run Powershell command and type ```dnvm list```  You should see a list of all your installed runtimes.  The one with a * under the active column is the runtime your using.

![image](https://cloud.githubusercontent.com/assets/7406381/12311466/16a0a238-ba4f-11e5-9393-5cd4e12feab7.png)

**Comment by Gillardo** [comment] 2016-01-13 23:46
That is when ur using the dnx command. Right click the project and go to properties for iis express i think

**Comment by qujck** [comment] 2016-01-13 23:51
1.0.0-rc2-16357 x86

**Comment by Gillardo** [comment] 2016-01-15 11:18
Can you try the x64 version?

**Comment by qujck** [comment] 2016-01-15 12:56
Sorry for the delay, I am AFK today, I will get to this as soon as I can.

**Comment by qujck** [comment] 2016-01-15 23:02
I've tried `dnvm install 1.0.0-rc2-16357 -arch x64`

> The server returned a 404 (NotFound). This is most likely caused by the feed not having the version that you typed.
Check that you typed the right version and try again. Other possible causes are the feed doesn't have a DNX of the
right name format or some other error caused a 404 on the server.
At C:\Users\Peter\.dnx\bin\dnvm.ps1:558 char:13
+             throw "The server returned a 404 (NotFound). This is most ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The server retu... on the server.:String) [], RuntimeException
    + FullyQualifiedErrorId : The server returned a 404 (NotFound). This is most likely caused by the feed not having
   the version that you typed. Check that you typed the right version and try again. Other possible causes are the fe
  ed doesn't have a DNX of the right name format or some other error caused a 404 on the server.

and `dnvm install latest -arch x64` says 

> Determining latest version
'dnx-clr-win-x64.1.0.0-rc1-update1' is already installed in C:\Users\Peter\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-update1.

I've also run `dnvm update-self`

**Comment by Gillardo** [comment] 2016-01-16 06:56
Rc2 is a nightly build so u need to run command with -u parameter. Try ```dnvm upgrade -u -arch x64```

**Comment by qujck** [comment] 2016-01-16 17:39
Well that install worked. I now have the latest x64 rc2 and both code samples (the one you uploaded and the version where I removed Simple Injector) work fine. Can you try it with todays latest build?

The one change I made was in the project properties, I checked *Use Specific Runtime* and selected the new runtime version that I just installed.

**Comment by qujck** [comment] 2016-01-16 19:21
Okay, I figured out that IIS Express appears to keep hold of the first assembly that it compiled and that's why I continued to get the error after removing Simple Injector.

**Comment by Gillardo** [comment] 2016-01-16 19:30
@qujck This is good news!! At least your seeing the same issue now. So it is a problem with SI then?

**Comment by qujck** [comment] 2016-01-16 21:51
All I currently know is that It's a problem with object lifetimes.

**Comment by qujck** [comment] 2016-01-17 16:27
I have it working but I am not happy with the solution. 

I have created a couple of new extension methods for registering stuff with a scoped lifestyle (which is after all what the `DbContext` should be:

```csharp
public static void CrossWireDefaultScope<TService>(
    this Container container, 
    IApplicationBuilder applicationBuilder) where TService : class
{
    var registration = Lifestyle.Scoped.CreateRegistration(
        () => GetScopedInstance<TService>(container),
        container);

    container.AddRegistration(typeof(TService), registration);
}

private static TService GetScopedInstance<TService>(Container container)
{
    return container.GetInstance<IServiceScope>()
        .ServiceProvider
        .GetRequiredService<TService>();
}
```

And updated the `container` registrations:

```csharp
container.CrossWire<IServiceScopeFactory>(app);
container.Register(
    () => container.GetInstance<IServiceScopeFactory>().CreateScope(),
    Lifestyle.Scoped);
container.CrossWireDefaultScope<ApplicationDbContext>(app);
```

The problem we have here is that we are creating an instance of `IServiceScope` to keep the cross wired items alive within the context of the ASP.NET scope but this is not the same instance of `IServiceScope` the ASP.NET container is using internally. It is entirely possible to get 2 instances of `ApplicationDbContext` for a single request which is not good at all. 

Although this code works for your example I do not recommend using it as is ..

**Comment by Gillardo** [comment] 2016-01-20 12:54
@qujck Although this works on the sample i sent you, i am still facing the same issue on another method.  Will come up with an example shortly

**Comment by Gillardo** [comment] 2016-01-20 17:12
@qujck I have been working on a sample, and thought i would ask the question on another site, if you could actually use another DI with their software.  They said this, which i believe is incorrect, but wanted to double check with you, as this is not recommended on the documentation.

https://github.com/openiddict/core/issues/51#issuecomment-173275451

**Comment by qujck** [comment] 2016-01-20 21:32
My interpretation of their remarks is that they are recommending you use an adapter which is not something you are likely to see for Simple Injector. I also don't have any other solution to offer, it may be the case the Simple Injector and OpenIdDict will not be easily integrated.

**Closed** 2016-01-21 05:42 UTC
