### ISSUE TITLE
Guidance for integrating with Azure Functions 3.0

### ISSUE THREAD

**Issue by CasperWSchmidt** [simpleinjector/SimpleInjector#894] opened 2021-02-10 13:31 UTC
> **ADMINISTRATOR's NOTE:** There's an [Azure Functions Integration](https://simpleinjector.org/azurefunctions) page. This demonstrates how to integrate Simple Injector with  Azure Functions v3.

A lot has happened since many of the Azure Functions related issues here. Azure Functions are no longer required to be static classes with static method(s) and DI can be customized (using configuration) by extending `FunctionsStartup`. Therefore I'm looking to integrate Simple Injector with MS.DI with cross wiring. My current use case is to get access to the current user (from `HttpContext`) in an application component deeper in the object graph (so propagating it down the stack as a method parameter is not very pretty). I have created an IUserService abstraction with an implementation like this:
``` c#
public class UserService : IUserService
{
    private readonly IHttpContextAccessor httpContextAccessor;

    public UserService(IHttpContextAccessor httpContextAccessor)
    {
        this.httpContextAccessor = httpContextAccessor;
    }

    public User GetCurrentUser()
    {
        var claimsPrincipal = httpContextAccessor.HttpContext?.User;

        var userName = claimsPrincipal?.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Upn)?.Value;
        var name = claimsPrincipal?.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value;

        return new User(name, userName);
    }
}
```

In FunctionsStartup I'm adding HttpContextAccessor and SimpleInjector:
``` c#
public override void Configure(IFunctionsHostBuilder builder)
{
    var configuration = builder.GetContext().Configuration;
    var serviceCollection = builder.Services;
    var container = new Container();
    
    serviceCollection
        .AddHttpContextAccessor()
        .AddSimpleInjector(container);
    serviceCollection
        .BuildServiceProvider(true)
        .UseSimpleInjector(container);
    
    // Handles registrations of application components
    Setup(container, configuration);
}
```
The issue is that when firing up the Azure Function locally I get the following error:

> A host error has occurred during startup operation '69997a2d-8526-49a2-8a76-df5e0c0a5f45'.
func: Invalid host services. Microsoft.Azure.WebJobs.Script.WebHost: The following service registrations did not match the expected services:
[Invalid] ServiceType: Microsoft.Extensions.Hosting.IHostedService, Lifetime: Singleton, ImplementationFactory: System.Func`2[System.IServiceProvider,Microsoft.Extensions.Hosting.IHostedService].
Value cannot be null. (Parameter 'provider')

As far as I can see this error comes from the following code from SimpleInjector.Integration.ServiceCollection v.5.2.0:

``` c#
private static void HookAspNetCoreHostHostedServiceServiceProviderInitialization(
      SimpleInjectorAddOptions options)
{
  options.Services.AddSingleton<IHostedService>(
    (Func<IServiceProvider, IHostedService>) (provider =>
  {
    options.SetServiceProviderIfNull(provider);
    return (IHostedService)new SimpleInjectorServiceCollectionExtensions
        .NullSimpleInjectorHostedService();
  }));
}
```

I'm not sure if the problem is that the provider I create in `Configure` is not the same provider as the one actually used by the rest of the Azure Functions runtime?

Anyway, I'm looking for a possibility of integrating Simple Injector with Azure Functions or updated best practices regarding this topic.

**Comment by CasperWSchmidt** [comment] 2021-02-10 13:50
BTW, I read #652 but it doesn't quite feel right to retrieve the instance of `UserService` from all Azure Functions to set the current `HttpContext` (or similar).

**Comment by dotnetjunkie** [comment] 2021-02-10 14:41
And did you read https://github.com/simpleinjector/SimpleInjector/issues/536?

**Comment by dotnetjunkie** [comment] 2021-02-10 20:11
> As far as I can see this error comes from the following code from SimpleInjector.Integration.ServiceCollection v.5.2.0:

Can you please include the full stack trace?

**Comment by dotnetjunkie** [comment] 2021-02-10 22:01
Unfortunately, your integration code will not work. You are creating an `IServiceProvider` using `BuildServiceProvider` to finish the Simple Injector integration. This will, however, not be the same service provider as Azure Functions will use. It will call `BuildServiceProvider` again.

A good place to finish the Simple Injector integration seems to be missing from Azure Functions (or at least, I coudn't find a proper one). I found one very ugly hack that could do the trick until Azure Functions contains better support for this.

This is what you can do:

``` c#
public class Startup : MyFunctionsStartupBase
{
    private readonly Container container = new Container();

    public override void ConfigureServices(IServiceCollection services)
    {
        this.container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

        services.AddSimpleInjector(this.container, options =>
        {
            // Add some options (optional):
            options
                .AddLogging();
        });
        
        // Remove the hosted service that Simple Injector added. This causes trouble for AF.
        // Unclear to me why AF can't cope with this.
        services.Remove(services
            .Last(s => s.ServiceType == typeof(Microsoft.Extensions.Hosting.IHostedService)));
    }

    public override void Configure(IServiceProvider app)
    {
        app.UseSimpleInjector(this.container);
    }
}

// Base class to hide the uglyness
public abstract class MyFunctionsStartupBase : FunctionsStartup
{
    public abstract void ConfigureServices(IServiceCollection services);

    public abstract void Configure(IServiceProvider app);

    public override void Configure(IFunctionsHostBuilder builder)
    {
        this.ConfigureServices(builder.Services);

        // HACK: This allows calling Configure after the service provider has been built.
        var service = builder.Services[0];
        builder.Services[0] = ServiceDescriptor.Singleton(service.ServiceType, p =>
        {
            this.Configure(p);
            return service.ImplementationInstance;
        });
    }
}
```

This `Startup` class mimics the `Startup` of ASP.NET Core with its `ConfigureServices` and `Configure` methods. This makes the integration very similar. The hack is hidden in the base class. It decorates one specific MS.DI registration in such way that, when that service is resolved (which happens to be `Microsoft.Extensions.Hosting.IHostingEnvironment`), the integration can be completed. This works, because `IHostingEnvironment` is one of the first services that is being resolved by Azure (I tested this locally).

Do note that here be dragons. This is a fragile hack. In case in the future, `IHostingEnvironment` isn't the first registration, or isn't resolved any longer, this will break. But again, we'll likely have better integration points at that time.

Do note that this integration is still not complete. There are two shortcomings:

* Azure Functions are not resolved. This requires some sort of `IAzureFunctionsActivator` abstraction, which Azure seems to lack.
* Although an Azure Function class is resolved in an `IServiceScope`, Simple Injector will *not* use that scope when you start calling `Container.GetInstance<T>()`. When Simple Injector resolves a Scoped cross-wired framework component, it will create a new `IServiceScope` (and cache it in its own `Scope`). This might not be a problem; there are not many Scoped framework registrations out of the box. But still something to be aware of.

**Comment by CasperWSchmidt** [comment] 2021-02-11 12:16
> And did you read #536?

Yes I did, that's what I meant when I said "A lot has happened since many of the Azure Functions related issues here" :) The approach suggests a static container with static initialization, which is no longer required because we now have the FunctionsStartup.Configure hook.

About the stack trace, there is none :( - just the mentioned error message in the debug console. I tried debugging the extension methods AddSimpleInjector and UseSimpleInjector and that is where I saw the code that had a matching signature to the one in the error message.

Thanks for confirming my theory that the issue is that the service provider instance handed to Simple Injector is not the same as the one used by MS.DI and therefore it does not work. I will take this issue to the AZ repo and see if we can get better support for this.

Instead of adding dragons to production, I guess I will have to do the manual initialization in the AZ method (after manually beginning a new scope...) as suggested in one of the other issues.

Btw. from what I have read, it should be possible to override the default IJobActivator instance, I just can't find the blog post anywhere right now (for Azure Functions - there are plenty for WebJobs) :( This would allow setting up scopes for each function invocation

**Comment by dotnetjunkie** [comment] 2021-02-11 12:56
Let's keep this issue open, because I think it's good to keep the conversation going. Others might have input as well that might allow us to improve the situation we're in.

**Comment by dotnetjunkie** [comment] 2021-02-11 13:02
> About the stack trace, there is none :( - just the mentioned error message in the debug console.

The exception you experienced is caused by the registration of the `IHostedService` inside the `.AddSimpleInjector` extension method. For some reason that is unclear to me, Azure Functions can't handle such registration, which is what causes the exception.

>  I will take this issue to the AZ repo and see if we can get better support for this.

Please post a link; I'm very interested in following that conversation.

> I guess I will have to do the manual initialization in the AZ method (after manually beginning a new scope...) as suggested in one of the other issues.

Downside of what the other issues suggest, there is in that case no integration between Simple Injector and MS.DI, i.e. Simple Injector will not cross-wire MS.DI dependencies. But you can always cross-wire dependencies by hand, and my bet is that your application doesn't need that many framework dependencies to run.

> Btw. from what I have read, it should be possible to override the default IJobActivator instance, I just can't find the blog post anywhere right now (for Azure Functions - there are plenty for WebJobs) :( This would allow setting up scopes for each function invocation

If you find more information, let me know. I'm interested to see what things we can do to get the integration rolling.

**Comment by CasperWSchmidt** [comment] 2021-02-11 14:06
Good idea to keep the conversation going. I think I just found one of the "blog posts" I read: https://github.com/Azure/azure-functions-host/issues/4410. I'm just reading through issues in that repo to make sure I'm not suggesting something that has already been asked.

**Comment by CasperWSchmidt** [comment] 2021-02-12 07:27
>Downside of what the other issues suggest, there is in that case no integration between Simple Injector and MS.DI, i.e. Simple Injector will not cross-wire MS.DI dependencies. But you can always cross-wire dependencies by hand, and my bet is that your application doesn't need that many framework dependencies to run.
I'm not sure how to cross-wire dependencies by hand when I do not have access to the correct instance of IServiceProvider? Unless you mean that I'll have to do something similar to [this](https://github.com/simpleinjector/SimpleInjector/issues/652#issuecomment-453435266)

Btw. issue in Azure Functions Runtime repo is up now, linking back to this issue for details.

**Comment by dotnetjunkie** [comment] 2021-02-12 10:02
Automatic cross-wiring is enabled when you call `.AddSimpleInjector`. However, if you don't configure the Simple Injector integration explicitly, it will always create a new `IServiceScope` when resolving `Transient` and `Scoped` instances from MS.DI. This might not be a problem, but this does mean that the resolve from Simple Injector lives in its own bubble. If you want this to be different, you will have to override the `SimpleInjectorAddOptions.ServiceProviderAccessor` property with something specific to Azure Functions.

Here's a prototype:

``` c#
public class Startup : FunctionsStartup
{
    private readonly Container container = new Container();

    public override void Configure(IFunctionsHostBuilder builder)
    {
        var services = builder.Services;

        // Special integration classes (see below). Resolver needs to be
        // injected into every Azure Function class.
        services.AddScoped<Resolver>();
        services.AddSingleton<Resolver.Completion>();

        services.AddSimpleInjector(this.container, options =>
        {
            // Override the default ServiceProviderAccessor
            var accessor = new Resolver.Accessor(
                options.ServiceProviderAccessor);
            options.ServiceProviderAccessor = accessor;
            services.AddSingleton(accessor);
        });

        // Remove the hosted service that Simple Injector added. Hosted services are not supported.
        services.Remove(services
            .Last(s => s.ServiceType == typeof(Microsoft.Extensions.Hosting.IHostedService)));
    }
}

public sealed class Resolver : IDisposable
{
    private readonly Container container;
    private readonly Scope scope;

    public Resolver(
        Completion completor, // don't remove this dependency, it calls .UseSimpleInjector()
        Container container,
        IServiceProvider serviceScope,
        Accessor accessor)
    {
        this.container = container;

        // Set the current service scope for Simple Injector to cross wire from.
        accessor.Current = serviceScope;

        this.scope = AsyncScopedLifestyle.BeginScope(container);
    }

    public T Resolve<T>() where T : class => this.container.GetInstance<T>();

    // You probably want DisposeAsync to be called, but I didn't succeed in
    // getting Azure Functions to dispose anything asynchronously.
    public void Dispose() => this.scope.Dispose();

    public sealed class Completion
    {
        public Completion(IServiceProvider rootProvider, Container container)
        {
            // Complete the Simple Injector integration
            rootProvider.UseSimpleInjector(container);

            container.Verify();
        }
    }

    public sealed class Accessor : IServiceProviderAccessor
    {
        private readonly IServiceProviderAccessor baseAccessor;

        public Accessor(IServiceProviderAccessor baseAccessor) =>
            this.baseAccessor = baseAccessor;

        private readonly AsyncLocal<IServiceProvider> current = new AsyncLocal<IServiceProvider>();

        public IServiceProvider Current
        {
            get => this.current.Value ?? this.baseAccessor.Current;
            set => this.current.Value = value;
        }
    }
}
```

This runs with the following function:

``` c#
public class Function1
{
    private readonly Resolver resolver;

    // Injecting the Resolver automatically starts a Simple Injector scope that will use the
    // IServiceScope from which this function was resolved.
    public Function1(Resolver resolver)
    {
        this.resolver = resolver;
    }

    [FunctionName("Function1")]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req)
    {
        this.resolver.Resolve<ICommandHandler<CoolCommand>>().Handle(new CoolCommand());

        return new OkObjectResult("OK");
    }
}
```

I hope this helps.

**Comment by CasperWSchmidt** [comment] 2021-02-12 13:42
Thanks a lot. I was trying to create a decorator that would implement the same interface as my application components (using CQRS we have command and request handlers). The decorators would be registered in IServiceCollection and function as a bridge to components registered in Simple Injector like this:
```
public class SimpleInjectorCommandHandler<TCommand> : ICommandHandler<TCommand> where TCommand : ICommand
    {
        private readonly Container container;

        public SimpleInjectorCommandHandler(Container container)
        {
            this.container = container;
        }

        public async Task<CommandResult> Handle(TCommand command, CancellationToken cancellationToken = new CancellationToken())
        {
            await using (AsyncScopedLifestyle.BeginScope(container))
            {
                var realHandler = container.GetInstance<ICommandHandler<TCommand>>();
                
                return await realHandler.Handle(command, cancellationToken);
            }
        }
    }
```
Registration extension:
```
public static void UseCqrs(this Container container, IEnumerable<Assembly> assemblies, IServiceCollection? serviceCollection)
        {
            container.Options.DefaultScopedLifestyle ??= new AsyncScopedLifestyle();

            var assembliesToSearch = assemblies.ToList();
            container.Register(typeof(IRequestHandler<,>), assembliesToSearch, Lifestyle.Scoped);
            container.Register(typeof(ICommandHandler<>), assembliesToSearch, Lifestyle.Scoped);
            
            serviceCollection?.AddSingleton(typeof(ICommandHandler<>), 
                typeof(SimpleInjectorCommandHandler<>));
            serviceCollection?.AddSingleton(typeof(IRequestHandler<,>),
                typeof(SimpleInjectorRequestHandlerDecorator<,>));
            serviceCollection?.AddSingleton(container);
        }
```
Runs in a function like this:
```
public class Function1
{
    private readonly ICommandHandler<SomeCommand> commandHandler;

    public Function1(ICommandHandler<SomeCommand> commandHandler)
    {
        this.commandHandler = commandHandler;
    }

    [FunctionName("Function1")]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req)
    {
        commandHandler.Handle(new SomeCommand());

        return new OkObjectResult("OK");
    }
}
```
Fairly easy, but doesn't allow the full potential for cross-wiring. Specifically I can't inject the HttpContext into my UserService because it is registered as scoped, but no scope exists in the Run method above.

**Comment by dotnetjunkie** [comment] 2021-02-12 13:59
@CasperWSchmidt, that's super cool. Your adapter forwards the call from MS.DI to Simple Injector.

**Comment by CasperWSchmidt** [comment] 2021-02-12 14:02
@dotnetjunkie Indeed. Unfortunately it has severe limitations as mentioned above, so I will implement what you suggested (renaming Resolver etc. for making it more transparent)

**Comment by dotnetjunkie** [comment] 2021-03-06 13:15
@CasperWSchmidt you can mix both our approaches. That would lead you a Azure Function class that looks as follows:

``` c#
// Using record types, just for fun and succinctness 
public record Function1(ICommandHandler<CoolCommand> Handler)
{
    [FunctionName("Function1")]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req)
    {
        this.Handler.Handle(new CoolCommand());
        return new OkObjectResult("OK");
    }
}
```

This can be achieved by merging the `Resolver` and your command-handler adapter:

``` c#
public sealed class AzureFunctionsToSimpleInjectorCommandHandler<TCommand>
    : ICommandHandler<TCommand> where TCommand : ICommand
{
    private readonly Container container;
    private readonly IServiceProvider serviceScope;
    private readonly Accessor accessor;
    
    public SimpleInjectorCommandHandler(
        Completion completor, // don't remove this dependency, it calls .UseSimpleInjector()
        Container container,
        IServiceProvider serviceScope,
        Accessor accessor)
    {
        this.container = container;
        this.accessor = accessor;
        this.serviceScope = serviceScope;
    }

    public async Task<CommandResult> Handle(
        TCommand command,
        CancellationToken cancellationToken = new CancellationToken())
    {
        await using (AsyncScopedLifestyle.BeginScope(this.container))
        {
            // Set the current service scope for Simple Injector to cross wire from.
            accessor.Current = serviceScope;
        
            var realHandler = this.container.GetInstance<ICommandHandler<TCommand>>();
            
            return await realHandler.Handle(command, cancellationToken);
        }
    }
}
```

You need the following wiring:

``` c#
public class Startup : FunctionsStartup
{
    private readonly Container container = new Container();

    public override void Configure(IFunctionsHostBuilder builder)
    {
        var services = builder.Services;

        services.AddSingleton(accessor);
        
        services.AddScoped(
            typeof(ICommandHandler<>),
            typeof(AzureFunctionsToSimpleInjectorCommandHandler<>));

        services.AddSimpleInjector(this.container, options =>
        {
            // Use of hosted services is not supported by Azure Functions.
            options.EnableHostedServiceResolution = false; // Will be available in v5.3 (#15)
            
            // Override the default ServiceProviderAccessor
            var accessor = new Accessor(options.ServiceProviderAccessor);
            options.ServiceProviderAccessor = accessor;
            services.AddSingleton<Completion>();
        });
    }
}


public sealed class Completion
{
    public Completion(IServiceProvider app, Container container)
    {
        // Complete the Simple Injector integration
        app.UseSimpleInjector(container);

        container.Verify();
    }
}

public sealed class Accessor : IServiceProviderAccessor
{
    private readonly IServiceProviderAccessor baseAccessor;

    public Accessor(IServiceProviderAccessor baseAccessor) =>
        this.baseAccessor = baseAccessor;

    private readonly AsyncLocal<IServiceProvider> current = new AsyncLocal<IServiceProvider>();

    public IServiceProvider Current
    {
        get => this.current.Value ?? this.baseAccessor.Current;
        set => this.current.Value = value;
    }
}
```

**Comment by dotnetjunkie** [comment] 2021-03-12 14:47
I created a new [Azure Functions Integration](https://simpleinjector.org/azurefunctions) page. This demonstrates how to integrate Simple Injector with  Azure Functions v3.

**Comment by RyanMarcotte** [comment] 2021-03-13 16:50
Worth noting that DI for Azure Functions implementations [changed yet again when using NET 5](https://codetraveler.io/2021/02/12/creating-azure-functions-using-net-5/).  It now uses `HostBuilder`.  I was able to follow the same process used for [generic host integration](https://simpleinjector.readthedocs.io/en/latest/generichostintegration.html).

``` csharp
internal class Program
{
	private static async Task Main(string[] args)
	{
		var container = new Container();
		var host = new HostBuilder()
			.ConfigureAppConfiguration(configurationBuilder => configurationBuilder.AddCommandLine(args))
			.ConfigureFunctionsWorker((hostBuilderContext, workerApplicationBuilder) => workerApplicationBuilder.UseFunctionExecutionMiddleware())
			.ConfigureServices(services => services.RegisterInfrastructureAndApplicationComponents(container))
			.Build()
			.UseSimpleInjector(container);

		container.Verify();

		await host.RunAsync();
	}
}

internal static partial class ServiceCollectionExtensions
{
	public static void RegisterInfrastructureAndApplicationComponents(this IServiceCollection services, Container container, ILogger logger)
	{
		services.AddLogging();
		services.AddHttpClient();

		services.AddSimpleInjector(container);

		// RegisterMediatR is an extension method defined by the application that registers all MediatR-specific application components
		container.RegisterMediatR();

		// register other application components here
	}
}
```

I then have to explicitly retrieve components from the `IServiceProvider` included in `FunctionExecutionContext`.  In my case, it's MediatR's `ISender` implementation.

``` csharp
public class SampleFunction
{
	[FunctionName(nameof(SampleFunction))]
	public async Task<IActionResult> Run(
		[HttpTrigger(AuthorizationLevel.Function, HTTPMethod.POST, Route = null)] HttpRequestData request,
		FunctionExecutionContext executionContext,
		CancellationToken cancellationToken)
	{
		// TODO: parse HTTP request body

		var operationContext = executionContext.ToOperationContext();
		var parameters = new SampleFunctionRequestParameters(operationContext);
		return await executionContext.GetMediator().Send(parameters, cancellationToken).ToActionResult();
	}
}

internal static class FunctionExecutionContextExtensions
{
	// OperationContext is defined by the application and just holds a correlation ID field
	public static OperationContext ToOperationContext(this FunctionExecutionContext executionContext)
	{
		return new OperationContext(executionContext.InvocationRequest.InvocationId);
	}

	public static ISender GetMediator(this FunctionExecutionContext executionContext)
	{
		// executionContext.InstanceServices is IServiceProvider
		var container = executionContext.InstanceServices.GetRequiredService<Container>();
		var mediator = container.GetInstance<ISender>();

		return mediator;
	}
}
```

**Comment by dotnetjunkie** [comment] 2021-03-13 18:40
>  DI for Azure Functions implementations changed yet again when using NET 5.

Oh boy, not again :'(

**Comment by CasperWSchmidt** [comment] 2021-03-14 19:40
@RyanMarcotte this is only true for the out-of-process version of Azure Functions. It is similar to pretty much any other .Net Core program using HostBuilder. For .Net 6 (which will be LTS) it will be supported (confirmed by MS somewhere) as in-process like .Net Core 3.1 (probably as AZ v4) and for that I believe we will still have to use what we have above.

For out-of-process Azure Functions (nice addition by the way) we can do what ever we like, it's just a console application.

**Comment by RyanMarcotte** [comment] 2021-03-14 20:17
Correct @CasperWSchmidt , [NET 5 only provides the out-of-process option while NET 6 will (according to their roadmap) support both in-process and out-of-process options](https://techcommunity.microsoft.com/t5/apps-on-azure/net-on-azure-functions-roadmap/ba-p/2197916).  It may be useful for the Azure Function integration page to also link to the `HostBuilder` integration page for setting up the integration for the out-of-process option.

**Closed** 2022-01-10 20:14 UTC
Labels: question
