### ISSUE TITLE
Virus detected in SimpleInjector 3.1.2

### ISSUE THREAD

**Issue by Alovchin91** [simpleinjector/SimpleInjector#169] opened 2016-01-15 11:53 UTC
McAfee antivirus detects a virus in SimpleInjector 3.1.2 NuGet package: https://www.virustotal.com/ru/file/bd4d048b701f9fca4d7ff5ecd4da6d6ab1f2fa9d768c14bc941d8a87356f0a05/analysis/1452858167/
Because of this we cannot use it in our projects as our enterprise McAfee doesn't allow us to access the package.
Please do something to fix this in the next release. Thanks!

**Comment by dotnetjunkie** [comment] 2016-01-15 14:54
Please tell me what to fix exactly and what would cause McAfee to report this as 'suspicious', because as far as I'm concerned this is a false positive.

**Comment by Alovchin91** [comment] 2016-01-15 15:57
@dotnetjunkie If I knew what to fix exactly I would suggest a pull request :) If it's a false positive maybe you could submit the DLL or NuGet package to McAfee support. This issue doesn't occur with SimpleInjector 3.1.1 and even with 3.1.2-alpha2, so this is definitely because of some recent changes.

**Comment by TheBigRic** [comment] 2016-01-17 20:48
@Alovchin91 

I tested the package against several scanners including McAfee but none of them reported a virus, malware or whatever other possible infection. All used scanners updated with signatures from today.

Can you reproduce this on a pc outside of the corporate network? For instance on your personal pc, if you have one.

**Comment by Alovchin91** [comment] 2016-01-17 21:15
@TheBigRic I don't have McAfee at home, but I can say that Eset doesn't detect the package. I'll try again at work tomorrow with the latest McAfee's signatures.

**Comment by Alovchin91** [comment] 2016-01-18 07:51
@TheBigRic With the latest signatures, McAfee VirusScan Enterprise still detects this:
```
URL: https://api.nuget.org/packages/simpleinjector.3.1.2.nupkg
Media Type: application/vnd.ms-ooxml
Virus Name: McAfeeGW: BehavesLike.Win32.Suspicious.fh
```

**Comment by TheBigRic** [comment] 2016-01-18 09:12
@Alovchin91 I have no access to McAfee Enterprise. This seems the only scanner which detects the package. IMO it must be a false positive. And also a bit suprising that McAfee has different engines for the Enterprise and other versions....

According to [this link](http://www.mcafee.com/us/threat-center/resources/how-to-submit-sample.aspx) for your IT department it should be easy to submit a sample, using the McAfee ServicePortal/Platinum Portal. I will submit a sample also by email but I think we could get more speed if you would supply them with a sample also.

Keep us posted!

**Comment by Alovchin91** [comment] 2016-01-18 09:28
@TheBigRic Great, thanks for the link! I'll contact our IT department.

**Comment by TheBigRic** [comment] 2016-01-18 10:09
Response from McAfee labs:

> File Name|Findings|Detection|Type|Extra
> --------------------------|--------------------------------|-----------------------|------------|-----
> simpleinjector.3.1.2|inconclusive|||no   
> inconclusive [simpleinjector.3.1.2.nupkg]                                                          
> Automated analysis was not able to determine that this file is malware. This file is being sent for further processing and the DAT files will potentially be updated if detection of this sample is warranted.

So basically McAfee is inconclusive completely as the customer version and there own lab don't detect anything. By this submission I hope they won't update all .DAT signatures to makes this a detection, because as I'm currently concluding this is definitily a false positive. Maybe your IT department has made some extra configurations to harden the protection.

As far as i'm concerned this issue is closed for research from our side. 

Please let us know what your IT department finds in communications with McAfee.

**Comment by qujck** [comment] 2016-01-23 23:22
This issue has come up again via nuget:

> We are having trouble installing 3.1.2. McAfee Security Gateway at our office is flagging this package as containing a virus. The prior version seemed to work fine. Has anyone else reported this issue?

**Comment by dotnetjunkie** [comment] 2016-01-23 23:25
I noticed. Can you point that guy at the github discussion? That should answer the question.

**Comment by dotnetjunkie** [comment] 2016-03-13 16:02
Would it be okay for me.to close this issue?

**Closed** 2016-04-02 14:09 UTC
Labels: question, task
