### ISSUE TITLE
Can I execute logic when a dependency instance is first resolved?

### ISSUE THREAD

**Issue by apetkovic** [simpleinjector/SimpleInjector#153] opened 2015-11-24 16:04 UTC
I've used `OnActivation` and `OnDeactivation` methods in Ninject to execute logic when an instance is first resolved. I checked the documentation and couldn't find anything like that for Simple Injector. I use this for things like handling events that are raised in a specific instance. Is there a way to extend Simple Injector and create this behavior?

**Comment by dotnetjunkie** [comment] 2015-11-24 16:24
The Simple Injector equivalent of `OnActivation` is [Container.RegisterInitializer](https://simpleinjector.org/ReferenceLibrary/?topic=html/M_SimpleInjector_Container_RegisterInitializer__1.htm). `RegisterInitializer` allows the registration of a delegate that will be invoked when an instance of the given type is created. Example:

``` c#
container.RegisterInitializer<IHandler>(handlerToInitialize => {
    handlerToInitialize.ExecuteAsynchronously = true;
});
```

The Simple Injector equivalent of `OnDeactivation` is a combination of `RegisterInitializer` and [Scope.WhenScopeEnds](https://simpleinjector.org/ReferenceLibrary/?topic=html/M_SimpleInjector_Scope_WhenScopeEnds.htm). Example:

``` c#
container.RegisterInitializer<IHandler>(handler => {
    var scope = container.DefaultScopedLifestyle.GetCurrentScope(container);
    scope.WhenScopeEnds(() => {
        DoSomethingInterestingOnDeactivation(handler);
    });
});
```

What this does is during initialization, get the current active scope and register a delegate that will be invoked when the scope ends (just before the scope disposes all scoped instances). If deactivation is something you need more often, you can also create the following extension method:

``` c#
public static void OnDeactivation<TService>(this Container container,
	Action<TService> onDeactivation) where TService : class {
	container.RegisterInitializer<TService>(instance => {
		var scope = container.DefaultScopedLifestyle.GetCurrentScope(container);
		scope.WhenScopeEnds(() => { onDeactivation(instance); });
	});
}
```

This extension method can be used as follows:

``` c#
container.OnDeactivation<IHandler>(handler => DoSomethingInterestingOnDeactivation(handler));
```

Do note however that activation and deactivation are concepts that you should rarely need. You should rarely need them because:

 - Activation means components have [Temporal Coupling](http://blog.ploeh.dk/2011/05/24/DesignSmellTemporalCoupling/), which is a design smell.
 - Most of the deactivation logic of a component that needs deterministic clean-up should go into the component's `Dispose` method.
 - For third party components, you can usually register a simple delegate that will do the creation and activation in one single operation.

If you're in doubt, please show your configuration and classes. This would allow me to feedback on your design.

**Comment by apetkovic** [comment] 2015-11-24 16:59
RegisterInitializer should work for me. Just to get a better idea of how I'm using it... 

I have a business logic layer that is shared across a few web applications each using different technologies (mvc, web api, and wcf). My business logic layer doesn't implement any type of exception handling. All exceptions bubble up to the application level, where they are logged by some exception monitoring system (either elmah, raygun, or app insights). There are some scenarios however, where the exception isn't bubbled up due to an asynchronous request or executing logic on a separate thread. In those cases I implement an OnFailure event on the class that fires when an exception is returned. I handle that OnFailure event at the application level where my dependencies are registered (using OnActivation) and the exception monitoring is already configured. 

I suppose to get around this I could inject an IExceptionLogger that implements each of the different exception monitors at the application level. But that now becomes a required dependency. If I don't want to log exceptions I still need to create an empty implementation of IExceptionLogger and inject it.

**Comment by dotnetjunkie** [comment] 2015-11-24 17:09
A more common approach of handling this scenario is by using decorators, but that might require a redesign if your application isn't designed around a few generic abstractions.

**Comment by apetkovic** [comment] 2015-11-24 19:10
Thanks! I'll look for some examples.

**Comment by apetkovic** [comment] 2015-11-24 22:34
I've decided to go ahead and implement the decorator approach. It was pretty simple to do under my current architecture. I'm basically just creating a wrapper implementation that handles all the events and then re-raises them to remain SOLID for any other chained decorators.The issue I'm running into now is due to a combination of some of the advanced scenarios. I've implemented the MostResolvableConstructorBehavior due to classes with multiple constructors. Now I receive a null reference exception when trying to resolve a constructor for my decorator implementation. The reason for this is the MostResolvableConstructorBehavior.CanBeResolved method can't resolve my type with container.GetRegistration. It was registered with container.RegisterDecorator which apparently doesn't return anything through container.GetRegistration.

**Comment by dotnetjunkie** [comment] 2015-11-25 06:30
Great to hear that your architecture enables the use of decorators. I use architectures as described [here](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91), [here](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92) and [here](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=95) and that means that in my case that would mean that I have to write *at most* 2 decorators to implement the behavior you describe.

About the `MostResolvableConstructorBehavior`, please be warned that having components with [multiple constructors is an anti-pattern](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=97), so you are better of refactoring these components. Removing all ambiguous constructors will remove the need to have a custom `IConstructorResolutionBehavior` and will solve the `NullReferenceException` problem you are getting.

**Comment by dotnetjunkie** [comment] 2015-11-25 22:22
But eitherway, I'm quite interested to see how you managed to get that exception. Can you link me to the `MostResolvableConstructorBehavior` code you used and can you post a complete stack trace of the error?

**Comment by apetkovic** [comment] 2015-12-01 21:17
I've moved away from the `MostResolvableConstructorBehavior` and am using the default single constructor behavior per your advice.

Anyhow.. my vs solution is too large to send, but basically it's a combination of these 3 things that causes the exception.
1. Use the sample `MostResolvableConstructorBehavior`
2. Use `Container.RegisterCollection` (not `Container.Register`) to register a collection
3. Use `Container.RegisterDecorator` to register a decorator for the same interface registered with `RegisterCollection`

The decorator then fails to inject properly. `MostResolvableConstructorBehavior.CanBeResolved` returns False because it's using `Container.GetRegistration` to find the registered interface in the container. Registering an interface using both `Container.RegisterCollection` and `Container.RegisterDecorator` doesn't return a result with `Container.GetRegistration`. When it can't find a constructor with any registered types it causes an exception.

If you can't replicate the behavior following the steps above then I'll send some actual code.

On a side note... moving from Unity and Ninject took a little bit of work but so far I'm really enjoying Simple Injector. I'll be deploying and monitoring a couple applications in my production environment; but I expect it to easily outperform the other DI libraries. Thanks so much for your help with some of the more advanced scenarios and concepts.

**Comment by dotnetjunkie** [comment] 2015-12-02 07:42
I can confirm this bug. I'm not yet sure whether this is a problem with the implementation of the `MostResolvableConstructorBehavior` class or a bug that originates from the core library. Further investigation should determine that. I did create an issue for this bug though: https://github.com/simpleinjector/SimpleInjector/issues/155.

**Comment by dotnetjunkie** [comment] 2015-12-02 21:17
Note that I described the problem with the MostResolvableConstructorBehavior [here](https://github.com/simpleinjector/SimpleInjector/issues/155).

**Closed** 2016-02-18 01:41 UTC
Labels: question
