### ISSUE TITLE
Entity framework 6 dynamic connections string using Simple Injector

### ISSUE THREAD

**Issue by wheeeels** [simpleinjector/SimpleInjector#518] opened 2018-02-26 14:59 UTC
Hello,
I have a unit of work with the repository pattern with simple injector implemented and I need to change my connection string dynamically. Currently the connection string is taken from the web config. I need the connection string be taken from the database.

So I will have a database with the ASP.Net Identity and the connections strings by user  (and other configurations needed for my application) and different databases depending on the client. So when a call  is made, I query the configuration database for the connection string for the current user (the current unit of work injected points to the configuration database), and somehow instantiate a new scoped unit of work with the new connection string connection using the DI container.  Any ideas how i can achieve this using my current setup?

My repositories and Unit of work are as follows.

``` c#
public abstract class DataRepositoryBase<TEntity, TContext> : IDataRepository<TEntity>
    where TEntity : class, IObjectStateEntity, new()
    where TContext : class, IDbSimpleContextAsync
    {
        protected DataRepositoryBase(TContext context)
        {
            Context = context;            
        }

        public virtual TContext Context { get; }

        public IEnumerable<TEntity> Get()
        {
            return Context.Get<TEntity>();
        }

        public TEntity Get(object id)
        {
            return Context.Find<TEntity>(id);
        }
}

public class SomeRepository : DataRepositoryBase<SomeObject, IContext>, ISomeRepository
{
    public SomeRepository (IContext context) : base(context)
    {
    }
}

public abstract class UnitOfWorkBase : IUnitOfWork
{
    private IDbSimpleContextAsync _dbContext;

    protected UnitOfWorkBase(IDbSimpleContextAsync dbContext)
    {
        _dbContext = dbContext;
    }

    public int SaveChanges()
    {
        return _dbContext.SaveChanges();
    }

    public Task<int> SaveChangesAsync()
    {
        return _dbContext.SaveChangesAsync();
    }
}

public class UnitOfWork : UnitOfWorkBase, IUnitOfWork
{
    private ISomeRepository _someRepository
    private readonly IContext _dbContext;

    public UnitOfWork(IContext dbContext) : base(dbContext)
    {
        _dbContext = dbContext;
    }

    public ISomeRepository SomeRepository => _someRepository ?? (_someRepository = new SomeRepository(_dbContext));
}

public class BookingBusiness : IBookingBusiness
{
    protected IAllotmentUnitOfWork UnitOfWork { get; }

    public AllotmentBusinessBase(IUnitOfWork unitOfWork)
    {
        UnitOfWork = unitOfWork;
    }

    ...
    business methods here
    ...
}
```

**Comment by dotnetjunkie** [comment] 2018-02-26 15:03
Duplicate of https://stackoverflow.com/questions/48990383/entity-framework-6-dynamic-connections-string-using-di

**Closed by dotnetjunkie** 2018-02-26 15:03 UTC

**Comment by wheeeels** [comment] 2018-02-26 15:06
That question is mine :) but since this could be more specific to simple injector (since i'm using it) i thought of bringing it here too
