### ISSUE TITLE
Could not install package 'SimpleInjector 3.2.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0

### ISSUE THREAD

**Issue by ravensorb** [simpleinjector/SimpleInjector#270] opened 2016-07-14 17:49 UTC
It worked without issue in 3.1.4 -- as of 3.2.0 it no longer works.

**Comment by dotnetjunkie** [comment] 2016-07-14 18:00
What you are experiencing is the awesomeness of the NuGet package manager.  It has selected the new .NETStandard target over the PCL target that is compatible with Xamarin.

I'm not sure how to fix this;IMO  this is a Nuget issue. You can copy the SimpleInjector.dll from the PCL directory of the Nuget package into your project and reference it directly, until the problem has been resolved.

**Comment by ravensorb** [comment] 2016-07-14 18:04
Why not just update the nuspec to also include the targets that work for Xamarin (droid and ios).  That is what I did for XLabs

**Comment by dotnetjunkie** [comment] 2016-07-14 18:07
You can send a pull request?

**Comment by ravensorb** [comment] 2016-07-14 18:09
love to - just too many other priorities right now :)

**Comment by dotnetjunkie** [comment] 2016-07-14 18:10
I've got the same problem :)

**Comment by dotnetjunkie** [comment] 2016-07-14 19:33
Possible duplicate of https://github.com/simpleinjector/SimpleInjector/issues/262

**Comment by dotnetjunkie** [comment] 2016-09-29 19:59
Should be fixed with v3.2.2

**Closed by dotnetjunkie** 2016-09-29 19:59 UTC
Labels: task
