### ISSUE TITLE
Best Practice For Injecting Log4Net Into .NET's WebApiExceptionLogger?

### ISSUE THREAD

**Issue by jwbats** [simpleinjector/SimpleInjector#213] opened 2016-04-05 10:55 UTC
.NET's WebApiExceptionLogger is a class that you register in order to process exceptions in WebApi controllers.

You register it as follows in WebApiConfig.cs:

``` c#
config.Services.Add(typeof(IExceptionLogger), new WebApiExceptionLogger());
```

It has a default constructor. I can't add an additional constructor, because SimpleInjector forces me to use one.

I don't mind enforcing one constructor per class, but now I am asking myself what the best way is to inject LogNet's ILog into this class?

The WebApiExceptionLogger instance is created and registered before the SimpleInjector initialization runs. So it looks like any kind of dependency injection at all (constructor, method, property) is out of the question.

I have considered resolving the dependency via SimpleInjector. But that would be the service locator pattern. And SimpleInjector doesn't allow me to access the container anyway, because it enforces the best practices in patterns. Besides... if I'm going to do service location, I might as well use Log4Net's default getter method. Kind of defeats the purpose.

This seems like an impossible situation right here.

What's my best option for getting WebApiExceptionLogger to work with SimpleInjector anyway?

**Comment by dotnetjunkie** [comment] 2016-04-05 11:11
The [IExceptionLogger](https://msdn.microsoft.com/en-us/library/system.web.http.exceptionhandling.iexceptionlogger%28v=vs.118%29.aspx) abstraction is part of the System.Web.Http assembly, but I can't find the `WebApiExceptionLogger` class you are talking about. From which library is this `WebApiExceptionLogger` coming from?

Besides this, it's unclear to me what it is you would like to achieve and why you need Simple Injector for this. Also note that Simple Injector [doesn't force](https://simpleinjector.readthedocs.org/en/latest/extensibility.html#overriding-constructor-resolution-behavior) classes to have a default constructor, but having a single constructor is the [sensible default](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=97).

In your case I'd expect your registration to look something like this:

``` c#
ILog logger = new MyLogger(); // create your logger here
config.Services.Add(typeof(IExceptionLogger), new WebApiExceptionLogger(logger));

var container = new Container();
container.RegisterSingleton<ILog>(logger);
```

`WebApiExceptionLogger` is not an application component, and since it is stored as singleton in Web API, it's not wise to resolve it from Simple Injector, because this might cause hidden problems such as [Captive Dependencies](http://blog.ploeh.dk/2014/06/02/captive-dependency/) that Simple Injector is unable to detect for you. Instead, view this `WebApiExceptionLogger` as an adapter or [Humble Object](http://xunitpatterns.com/Humble%20Object.html).

**Comment by jwbats** [comment] 2016-04-05 11:21
I mistakenly thought WebApiExceptionLogger was a .NET library class. Turns out I made it myself, but it implements .NET's ExceptionLogger. So I was really talking about ExceptionLogger instead.

I know Simple Injector does not enforce a single default constructor. If it would, it wouldn't be able to inject anything in the first place.

I don't **need** SimpleInjector for this, but I would have loved to see DI working all over my application. I'm injecting Log4Net without problems into my MVC controllers, whose OnException method can then use the injected Log4Net instance.

Being able to do this the same way in WebApi controllers would have made it consistent. But WebApi controllers don't have an overrideable OnException method. They require a class implementing the ExceptionLogger to handle this.

I'm trying to achieve dependency injection all over my app. I want to inject a logger into my error handling class so I can log my exceptions.

**Comment by dotnetjunkie** [comment] 2016-04-05 11:56
It's great to hear that you strive to apply Dependency Injection where you can. But please note that you don't always need the container to resolve instances for you. The container will help build up big complex object graphs, but when it comes to infrastructural adapters, creating those by hand is often prefered (and this not only holds when working with Simple Injector). So yes: you should use dependency (constructor) injection, but don't try to (ab)use the container to build up everything.

Can you show your `WebApiExceptionLogger` implementation?

**Comment by jwbats** [comment] 2016-04-05 12:32
**How** would I know when I am abusing SimpleInjector?

I try to prevent complex structures by preventing circular references. Not sure what else I could do about it.

What precisely do you mean by 'infrastructural adapters'? Could you provide an example?

My WebApiExceptionLogger implementation is pretty much what you'd expect. It currently looks like this:

```
	class WebApiExceptionLogger : ExceptionLogger
	{

		private ILog logger;

		public WebApiExceptionLogger(ILog logger)
		{
			this.logger = logger;
		}

		public override void Log(ExceptionLoggerContext context)
		{
			string strException = context?.ExceptionContext?.Exception?.ToString();
			this.logger?.Error(strException);
		}

		public virtual bool ShouldHandle(ExceptionHandlerContext context)
		{
			return true;
		}

	}
```

Why do you ask?

**Comment by dotnetjunkie** [comment] 2016-04-05 13:40
> How would I know when I am abusing Simple Injector?

That's actually a quite hard question to answer and a broad topic in general. You might start with [When should you use a container](https://simpleinjector.org/blog/2015/12/when-should-you-use-a-container/). While it is good to apply the Dependency Inversion Principle and the Dependency Injection pattern, you might not need a container at all.

As a general rule I think we can state:

> Services that are resolved by the container, should stay under control of the container. 

In your case, you wished to resolve `WebApiExceptionLogger`, while passing the resolved instance on to Web API. This can become problematic, because now Simple Injector loses control over managing its lifetime and is not able to diagnose any problems that can be caused by framework code that references that instance.

I think your `WebApiExceptionLogger` is a perfect example of a nicely implemented adapter. In your case it simply translates calls from a framework API (Web API) to an external library (NLog in this case). No application services are involved, which makes it really easy, because no callbacks to a container are needed.

**Closed** 2016-04-26 14:31 UTC
Labels: question

**Comment by meatgithub** [comment] 2016-04-28 11:15
@dotnetjunkie You had mentioned to do it by,
ILog logger = new MyLogger(); // create your logger here

However, IMO, this is not true dependency injection. If we use the new keyword, I believe it would be an anti-pattern. 

Also, if I am not using code but want to set it up using config file, how can I achieve this.

**Comment by dotnetjunkie** [comment] 2016-04-28 11:32
Hi @meatgithub,

I think you misunderstand what Dependency Injection and the Dependency Inversion Principle is about. It is not about removing all `new` keywords from your code base, but it's about centralizing creation and management of lifetime of your application's components. So we like to prevent having to use `new` in 'normal' application code, because this causes our code to have a dependency on a concrete type (which is something the Dependency Inversion Principle warns against). But somewhere in our code base we will have to reference this concrete type somewhere. This 'somewhere' is the centralized part and is part of the application start-up path. This centralized place is often referred to as the [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/).

So typically the only place you want to refer components is the Composition Root. Whether we manually new them up or delegate the creation to a DI library makes little difference; we still reference this concrete type.

Don't forget that applying the Dependency Injection pattern doesn't require the use of a DI library. You can use manually wired object graphs (a.k.a. [Pure DI](http://blog.ploeh.dk/2014/06/10/pure-di/)), which can make a lot of sense for smaller applications. Without the use of a DI library, you will have to `new` up instances yourself.

So using the `new` keyword is certainly not an anti-pattern, it depends on where we use it. In my example the creation of the `MyLogger` is clearly part of the Composition Root (where we configure our DI library), so the code is actually good practice.

> Also, if I am not using code but want to set it up using config file, how can I achieve this.

This question is unclear to me. You might want to create a new issue with this specific question, with the appropriate details and context.
