### ISSUE TITLE
How to register custom resolution logic so I could pass constructor arguments and choose between implementation classes at resolution time, based on context informations?

### ISSUE THREAD

**Issue by antonfirsov** [simpleinjector/SimpleInjector#161] opened 2015-12-16 02:09 UTC
Maybe it escaped my attention, but I could not find any code samples usable for this scenario. Can you help me, which examples, or documentation topics should I look at?

I need an API like this:

``` c#
public interface IViewModel // Marker
{
}

public class MyMagicViewModelCreator
{
    Container _container = new Container();

    public void RegisterFactory<TModel, TContext>(Func<TModel, TContext, IViewModel> factoryFunc)
    {
        throw  new NotImplementedException("????");
    }

    public IViewModel CreateViewModel<TModel, TContext>(TModel model, TContext context)
    {
        throw new NotImplementedException("????");
    }
}
```

So with the following test classes:

``` c#
public class FooModel
{
    public string Mood { get; set; }
}

public class HappyViewModel : IViewModel
{
    public HappyViewModel(FooModel model)
    {
        Model = model;
    }

    public FooModel Model { get; }
}

public class SadViewModel : IViewModel
{
    public SadViewModel(FooModel model)
    {
        Model = model;
    }

    public FooModel Model { get; }
}
```

I could do this:

``` c#
[TestMethod]
public void I_Wish_I_Could_Resolve_ViewModels_This_Way()
{
    MyMagicViewModelCreator creator = new MyMagicViewModelCreator();
    
    creator.RegisterFactory<FooModel, string>(
        (m, ctx) =>
        {
            return m.Mood.Contains("happy") && ctx.Contains("happy")?
                (IViewModel) new HappyViewModel(m) :
                new SadViewModel(m);
        });

    string context = "even if we are happy";

    FooModel model = new FooModel()
    {
        Mood = "Things can go really bad"
    };

    IViewModel viewModel = creator.CreateViewModel<FooModel, string>(model, context);
    Assert.IsNotNull(viewModel);
}
```

**Comment by antonfirsov** [comment] 2015-12-16 02:15
I'm very new at DI, SimpleInjector is the first container I started to use. Actually I don't know if DI containers are beeing designed to support these kind of scenarios or not, so maybe this is a lame question :)

**Comment by TheBigRic** [comment] 2015-12-17 22:49
You will have to give some context. Your termonolgy makes me think you're aiming WPF or a Windows Store App. If you could some more context I'm able to give you a more precise answer.

Without the context some things I noticed in your sample code.

It looks like your using runtime data to make decisions on which ViewModel to return. First of all, one of the reasons to use a DI container is to not have to created factories. While your supplied factory is rather simple it will start to grow rapidly, making it a maintenance nightmare. So 
 
 1. prevent making the object graph dependent on runtime data as you can read in depth [here] (https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99) (your FooModel is runtime data)
 2. If you would really need this, make this class part of your [composition root] (http://blog.ploeh.dk/2011/07/28/CompositionRoot/)
 3. Be really sure you aren't violating [LSP] (https://en.wikipedia.org/wiki/Liskov_substitution_principle)
 4. Last but not least let all the types you're application needs be instantiated/created by the container. Failing to do so, makes the container more or less obsolete.

IViewModel is indeed, as you noted, a marker interface. Marker interfaces are a good option for usage in DTO's. Marker interfaces for classes that need to be created by the container are not an option. Containers create classes by looking at the constructor of this specific type. If it has a registration, that is a key in the internal dictionary, for all parameters it can build the type and inject the constructor parameters. 
So ask yourself: If you would use a marker interface IViewModel with the following implementations:

``` c#
public class HappyViewModel : IViewModel { }
public class SadViewModel : IViewModel { }
``` 

And you would have this service:
``` c#
public class SomeService {
    private readonly IViewModel viewModel;    

    public SomeService(IViewModel viewModel) { 
           this.viewModel = viewModel;
     }
}
```  
 
Which IViewModel would you like to have injected by the container? Guess what, it doesn't know! 

So Simple Injector prevents these kinds of registrations. There are containers out there which are able of doing this with using keyed registrations. In fact, with some imagination, Simple Injector would be able to do this, but it is by design to prevent this by default, because in most cases needing this is just bad design. And Simple Injector [pushes developers towards good design](http://simpleinjector.readthedocs.org/en/latest/principles.html#push-developers-into-best-practices)

The solution however is quite simple. Make IViewModel opengeneric:

``` c#
public interface IViewModel<TModel>
{
    TModel Model {get;set;}
}
```

Now you could create these implementations:
``` c#
public class HappyViewModel : IViewModel<HappyModel>
{
    HappyModel Model {get;set;}
}
public class SadViewModel : IViewModel<SadModel>
{
    HappyModel Model {get;set;}
}
```

You can now inject the viewmodel you need, or both and make the runtime decision in the class where these viewmodels would be injecting into. But, big but, only do this if this is the scenario, having one runtime decision with 2 viewmodels. If this would grow, you
 1. Have to review the design and/or consult stackoverflow for help
 2. If there is really other better option, you can use a dispatches class in between. 

WIth some more context we probably can give you some advise what way would be the best.

**Comment by TheBigRic** [comment] 2015-12-24 09:31
@antonfirsov did this help you in any way and can we close the issue? 

Of you need more information, please leave a comment.

**Comment by antonfirsov** [comment] 2015-12-26 21:14
Hi,
your comment, together with Stevens blog post helped me a lot to pick up some basic knowledge about DI (before using it..), and I realized, I wanted to use the container in an inappropriate way. So thanks very much! :)

I ended up with a design where I use DI only to resolve collections of services implementing the following interface:

    public interface IViewModelActivator<in TModel, out TViewModel>
        where TViewModel : class, IViewModelFor<TModel>
    {
        TViewModel Create(TModel model, IViewModelScope scope);
    }

The logic for picking the right service from the collection is completely outside the container now, in a custom dispatcher class.

A few words about my context:
We have a domain with a complex inheritance graph, we are using WPF. Imagine a scenario, where we have a polymorphic collection of domain objects inherited from a TModel base class. If I pick an instance from the collection, there are several ViewModels (& Views) capable to display or edit my object. I want a design where I can select, initilaize, and "show" exactly one ViewModel for a specific TModel-inherited instance. The selection mechanism must be highly configurable, without forcing the developer to write boilerplate code.

**Closed** 2015-12-28 09:57 UTC
Labels: question
