### ISSUE TITLE
Concurrency bug when resolving a decorated instance (CyclicDependencyException is thrown)

### ISSUE THREAD

**Issue by smolyakoff** [simpleinjector/SimpleInjector#323] opened 2016-10-26 22:29 UTC
I have the following `GameHandler` class which uses SimpleInjector internally. Quite often I receive an exception when mediator instance tries to get the handler instance:

> The configuration is invalid. The type LaunchFleetHandler is directly or indirectly depending on itself. The cyclic graph contains the following types: LaunchFleetHandler.

Handler type varies on random. 

``` csharp
public class GameHandler : IGameHandler
{
    private static readonly Type HandlerInterfaceType = typeof(IAsyncRequestHandler<,>);
    private const string HandlerContextKey = "ConreignClientContext";
    private readonly IGameConnection _connection;
    private readonly Container _container;
    private readonly ActionBlock<WorkItem> _processor;
    private bool _isDisposed;

    public GameHandler(IGameConnection connection)
    {
        if (connection == null)
        {
            throw new ArgumentNullException(nameof(connection));
        }
        _connection = connection;
        _container = new Container();
        var mapperConfiguration = new MapperConfiguration(x => x.AddProfile<MappingProfile>());
        _container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();
        _container.RegisterSingleton<IMediator, Mediator>();
        _container.RegisterSingleton(new SingleInstanceFactory(_container.GetInstance));
        _container.RegisterSingleton(new MultiInstanceFactory(_container.GetAllInstances));
        _container.Register(() => (IHandlerContext) CallContext.GetData(HandlerContextKey), Lifestyle.Scoped);
        _container.RegisterSingleton(mapperConfiguration.CreateMapper());
        _container.Register(HandlerInterfaceType, new []{ typeof(LoginHandler).Assembly }, Lifestyle.Scoped);
        _container.RegisterDecorator(HandlerInterfaceType, typeof(AuthenticationDecorator<,>), Lifestyle.Scoped);
        _processor = new ActionBlock<WorkItem>(Process);
    }

    public IObservable<IClientEvent> Events => _connection.Events;

    public async Task<T> Handle<T>(IAsyncRequest<T> command, Metadata metadata)
    {
        EnsureIsNotDisposed();
        if (command == null)
        {
            throw new ArgumentNullException(nameof(command));
        }
        if (metadata == null)
        {
            throw new ArgumentNullException(nameof(metadata));
        }
        var source = new TaskCompletionSource<object>();
        var workItem = new WorkItem(source, command, metadata);
        _processor.Post(workItem);
        var result = await source.Task;
        return (T) result;
    }

    public void Dispose()
    {
        if (_isDisposed)
        {
            return;
        }
        _container.Dispose();
        _connection.Dispose();
        _isDisposed = true;
    }

    private void EnsureIsNotDisposed()
    {
        if (_isDisposed)
        {
            throw new ObjectDisposedException("GameHandler");
        }
    }

    private async Task Process(WorkItem workItem)
    {
        var traceId = Guid.NewGuid().ToString();
        var context = new HandlerContext(_connection, workItem.Metadata, traceId);
        CallContext.SetData(HandlerContextKey, context);
        try
        {
            using (var scope = _container.BeginExecutionContextScope())
            {
                var mediator = scope.GetInstance<IMediator>();
                var result = await mediator.SendAsync(workItem.Request);
                workItem.CompletionSource.SetResult(result);
            }
        }
        catch (Exception ex)
        {
            workItem.CompletionSource.SetException(ex);
        }
    }

    private class WorkItem
    {
        public WorkItem(TaskCompletionSource<object> completionSource, dynamic request, Metadata metadata)
        {
            CompletionSource = completionSource;
            Request = request;
            Metadata = metadata;
        }

        public TaskCompletionSource<object> CompletionSource { get; }
        public dynamic Request { get; }
        public Metadata Metadata { get; }
    }
}
```

It's quite obvious from the code that `LaunchFleetHandler` or any other command handler is not dependent on itself. Any clues why it could happen?

``` csharp
internal class LaunchFleetHandler : IAsyncRequestHandler<LaunchFleetCommand, Unit>
{
    private readonly IHandlerContext _context;

    public LaunchFleetHandler(IHandlerContext context)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }
        _context = context;
    }

    public async Task<Unit> Handle(LaunchFleetCommand message)
    {
        var player = await _context.User.JoinRoom(message.RoomId, _context.Connection.Id);
        await player.LaunchFleet(message.Fleet);
        return Unit.Value;
    }
}
```

**Comment by dotnetjunkie** [comment] 2016-10-27 06:12
From the code you posted, I can't find a cyclic dependency. My experience however is that Simple Injector is always right when it detects a cyclic dependency. Can you post a minimal example that reproduces the problem, i.e. some code that I can copy past and run locally?

**Comment by smolyakoff** [comment] 2016-10-27 06:21
Actually it would be quite difficult to provide an isolated repro as it's client-server app... This `GameHandler` is used from SignalR hub, so it's another separate instance and container per each SignalR client connection. So I suppose it might be a multithreading issue, as `CyclicDependencyValidator` is using ThreadLocal.

**Comment by dotnetjunkie** [comment] 2016-10-27 08:09
> If two containers with the same registrations are calling GetInstance on the same thread

Two containers can't have the same registration, since both `InstanceProducer` and `Registration` instances are container-specific. 

You can't call `GetInstance` on the same thread in parallel, since only one thing can happen concurrently on one thread.

> So I suppose it might be a multithreading issue, as CyclicDependencyValidator is using ThreadLocal.

Unlikely. That's the whole idea of the underlying ThreadLocal. Remember that resolving an object graph is *always* done on one single thread. There is no multi-threading or async stuff going on. This makes the use of ThreadLocal safe and valid.

**Comment by smolyakoff** [comment] 2016-10-27 15:59
Here is a repro. Several exception messages are printed in the console window. 
[ConsoleApplication1.zip](https://github.com/simpleinjector/SimpleInjector/files/556381/ConsoleApplication1.zip)

```csharp
using System;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;
using MediatR;
using SimpleInjector;
using SimpleInjector.Extensions.ExecutionContextScoping;

namespace ConsoleApplication1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var connections = Enumerable.Range(0, 15)
                .Select(x => new Connection())
                .ToList();
            var random = new Random();
            var tasks = Enumerable.Range(0, 1000)
                .Select(async i =>
                {
                    var k = random.Next(0, 15);
                    await connections[k].Handle(new Ping {Id = i.ToString()});
                })
                .ToArray();
            Task.WaitAll(tasks);
        }
    }

    public class Pong
    {
    }

    public class Ping : IAsyncRequest<Pong>
    {
        public string Id { get; set; }
    }

    public class CommandHandlerContext
    {
        public string TraceId { get; set; }
    }

    public class Decorator<TRequest, TResponse> : IAsyncRequestHandler<TRequest, TResponse>
        where TRequest : IAsyncRequest<TResponse>
    {
        private readonly IAsyncRequestHandler<TRequest, TResponse> _next;

        public Decorator(IAsyncRequestHandler<TRequest, TResponse> next)
        {
            _next = next;
        }

        public async Task<TResponse> Handle(TRequest message)
        {
            Console.WriteLine("Decorator before");
            var response = await _next.Handle(message);
            Console.WriteLine("Decorator after");
            return response;
        }
    }

    internal class CommandHandler : IAsyncRequestHandler<Ping, Pong>
    {
        private readonly CommandHandlerContext _context;

        public CommandHandler(CommandHandlerContext context)
        {
            _context = context;
        }

        public async Task<Pong> Handle(Ping message)
        {
            await Task.Delay(100);
            Console.WriteLine($"Ping from: {message.Id}. Trace id: {_context.TraceId}");
            return new Pong();
        }
    }

    public class Connection
    {
        private readonly ActionBlock<WorkItem> _processor;
        private readonly Container _container;

        public Connection()
        {
            _processor = new ActionBlock<WorkItem>(ProcessItem);
            _container = new Container();
            _container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();
            _container.RegisterSingleton<IMediator, Mediator>();
            _container.RegisterSingleton(new SingleInstanceFactory(_container.GetInstance));
            _container.RegisterSingleton(new MultiInstanceFactory(_container.GetAllInstances));
            _container.Register(() => (CommandHandlerContext) CallContext.GetData("HandlerContext"), Lifestyle.Scoped);
            _container.Register(typeof(IAsyncRequestHandler<,>), new[] {typeof(CommandHandler).Assembly},
                Lifestyle.Scoped);
            _container.RegisterDecorator(typeof(IAsyncRequestHandler<,>), typeof(Decorator<,>), Lifestyle.Scoped);
            _processor = new ActionBlock<WorkItem>(ProcessItem);
        }


        public async Task<T> Handle<T>(IAsyncRequest<T> command)
        {
            var source = new TaskCompletionSource<object>();
            var workItem = new WorkItem {Input = command, CompletionSource = source};
            _processor.Post(workItem);
            var result = await source.Task;
            return (T) result;
        }

        private async Task ProcessItem(WorkItem item)
        {
            var traceId = Guid.NewGuid().ToString();
            var context = new CommandHandlerContext {TraceId = traceId};
            CallContext.SetData("HandlerContext", context);
            try
            {
                using (var scope = _container.BeginExecutionContextScope())
                {
                    var mediator = scope.GetInstance<IMediator>();
                    var result = await mediator.SendAsync(item.Input);
                    item.CompletionSource.SetResult(result);
                }
            }
            catch (Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine(ex.Message);
                Console.ForegroundColor = ConsoleColor.White;
                item.CompletionSource.SetException(ex);
            }
        }

        private class WorkItem
        {
            public dynamic Input { get; set; }
            public TaskCompletionSource<object> CompletionSource { get; set; }
        }
    }
}
```

**Comment by dotnetjunkie** [comment] 2016-10-27 19:02
Thank you for this detailed post. I've been able to reproduce the issue using the supplied code. I'm currently investigating why this happens, but at this point I have no clue what is causing this. I keep you posted.

**Comment by dotnetjunkie** [comment] 2016-10-27 21:10
What I found out thus far:

- This concurrency bug is real and is located inside of Simple Injector.
- The bug can appear when a decorated instance is composed from multiple threads.
- The bug is not related to having multiple container instances; it's reproducible with a single container instance, although with the supplied example, the bug occurs less often with a single container instance.

Unfortunately I have no luck in spotting why this goes wrong. Since I can't imagine ThreadLocal values to leak from thread to thread (which means a bug in the .NET framework, which I find unlikely, since this would undermine the whole concept of ThreadLocal), it would mean that somehow under some race condition a cyclic reference is created. Everything however seems properly locked while the object graph is compiled, so I'm a bit dazzled on what is going on.

So I'm still investigating.

**Workaround**
In the meantime, until I located, fixed and published a fix, you can call `container.Verify()` after you're done configuring. Verify() will trigger the compilation of all expression trees for all registrations and does so single threaded. This prevents the problem because during the time the application requests the decorated instance, its delegate has been compiled down which prevents the possible race condition.

Doing so however will force you to change the registration for `CommandHandlerContext`, since registrations may never return `null`, while during verification it will be null (unless you set it manually before verification). The `Verify()` method will fail in that case. It is good to change the registration anyway, because it is important to have a [verifiable configuration](https://simpleinjector.readthedocs.io/en/latest/howto.html#verify-configuration) and you [don't want to inject runtime data into your application components](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99). Instead you can define a provider abstraction that allows returning the `CommandHandlerContext` and let Simple Injector manage the provider's lifestyle:

``` c#
// Located in a core assembly
interface ICommandHandlerContextProvider { CommandHandlerContext Current { get; } }

// Located in composition root
class CommandHandlerContextProvider : CommandHandlerContextProvider {
    public CommandHandlerContextProvider { get; set; }
}

container.Register<ICommandHandlerContextProvider, CommandHandlerContextProvider>(
    Lifestyle.Scoped);

private async Task ProcessItem(WorkItem item)
{
    var traceId = Guid.NewGuid().ToString();
    var context = new CommandHandlerContext { TraceId = traceId };
    try
    {
        using (_container.BeginExecutionContextScope())
        {
            var provider = (CommandHandlerContextProvider)
                _container.GetInstance<ICommandHandlerContextProvider>();
            provider.Current = context;
            var result = await _mediator.SendAsync(item.Input);
            item.CompletionSource.SetResult(result);
        }
    }
```

By no means I'm suggesting that you should always call `Verify()`; Calling Verify has a lot of overhead, and I regularly suggest developer to prevent calling it when the application runs in production, in case the application starts too slowly. However, this might be a great workaround for you until I published a patch release. Besides, without calling `Verify()` you lose one of the most powerful features that Simple Injector has to offer.

Few other comments about your code:

- You seem to create multiple container instances. Consider not doing this. There is a lot of overhead in the whole compilation process of a container, both CPU and memory usage. Resolving from the container is (or well... it should be) thread-safe. Resolving instances from the container is lock-free. There is no speed-up if you use one container per request.
- I am not familiar with `System.Threading.Tasks.Dataflow`, but it seems that `ActionBlock<T>` synchronizes access to it. I noticed that when I let all threads access the same `Connection` things got really slow. This is either caused by `ActionBlock<T>` or MediatR, but not by Simple Injector, because Simple Injector is lock-free in its happy-path. I have no idea what the function is of `ActionBlock<T>`, but I it seems just slowing things down and at the same time making the solution rather complex.

I hope this helps.

**Comment by smolyakoff** [comment] 2016-10-28 06:32
Thanks for the detailed answer and useful piece of advice! I had already changed the original design before I posted a repro here. Now I have a single container, singleton handlers and mediator. Context is passed as a part of the message.

**Comment by dotnetjunkie** [comment] 2016-11-01 20:31
I finally found out what was going on here. Some code in the `Registration` class of Simple Injector assumes that `System.ParameterInfo` objects are guaranteed by the CLR to be unique. Within the `Registration` class those `ParameterInfo` objects are used as key in a dictionary. Each `ParameterInfo` instance will get its own entry (since neither Equals nor GetHashCode are overridden by `ParameterInfo`). This internal dictionary is only used to apply decorators.

The assumption that `ParameterInfo` instances are unique within a single AppDomain is unfortunately incorrect.

Fact is that:

 - `System.Type` instances is guaranteed to be unique within an `AppDomain`, as stated by the documentation: "In reflection, all classes beginning with the word Runtime are created only once per object in the system and support comparison operations." ([source](https://msdn.microsoft.com/en-us/library/system.type(v=vs.110).aspx)). In other words, for each type, there will be at most one `System.Type` instance.
 - `System.MemberBase` instances are unique, although the documentation doesn't state this. The `MemberInfoCache<T>.Insert` method contains a `lock` that prevents multiple `MemberBase` instances to reference the same member (method, constructor, etc).
 - The documentation for `System.ParameterInfo` doesn't state any guarantees and the source code for `RuntimeConstructorInfo.GetParameters()` contains no protection whatsoever to prevent multiple threads from publishing `ParameterInfo` instances to the same parameter.

To me this seems like a bug in .NET because I see no reason why both `Type` and `MemberBase` would be guaranteed to be unique, while `ParamaterInfo` isn't.

Fact is however that this lack of guarantee is the cause of this bug in Simple Injector. Since Simple Injector protects creation of expression trees with a lock within a container instance, this bug will only show when multiple `Container` instances are created, that are not verified and container decorator registrations. The reason this shows up with multiple `Container` instances is because those `Container` instances can build generate their expression trees concurrently and can call `MemberBase.GetParameters()` at the same time. This can cause one single Container to use two `ParameterInfo` instances for the same physical parameter.

When the `ParameterInfo` instance that is returned from the `ConstructorInfo.GetParameters()` during the time the `Registration` object is created, doesn't match the `ParameterInfo` object that is returned from the `ConstructorInfo.GetParameters()` during the time the expression tree is composed, the `Registration` instance will lead to think that there is no 'parameter override' for the parameter (which is the decorator's decoratee parameter), which causes Simple Injector to use refer to the registration itself, which on its turn causes a cyclic dependency.
Since we don’t have to expect this ‘bug’ to be fixed in the .NET framework (and if it would, old versions would still be affected), this should be fixed in Simple Injector. The fix is rather simple: prevent the use of `ParameterInfo` as dictionary key, but use some value that can uniquely identify a parameter. A way to do this is using an anonymous type. For instance, the following code generates an anonymous type that can be used as key:
``` c#
new { parameter.Member, parameter.Name };
```
This will work, since `parameter.Member` is guaranteed to be unique, and within a member, each parameter has a unique name.

**Closed** 2016-11-01 20:52 UTC
Labels: bug, task
