### ISSUE TITLE
GetCurrentHttpRequestMessage

### ISSUE THREAD

**Issue by nvsoares** [simpleinjector/SimpleInjector#512] opened 2018-02-06 14:22 UTC
Hello. I'm involved in a web project where we use Simple Injector.

In this project we need to access the request (HttpRequestMessage) in several places. One such location is in the logging service. When the api receives a request, a CorrelationId is injected into the request header which we can then use throughout the request to log. We are unable to access the request in all locations and we think that the topic "Getting the current request's HttpRequestMessage" in your documentation would help but we are not achieving the desired result.
Can you help?

This is my Dependency Injection Setup:
```
public class DependencyInjection
    {
        public static Container Container;
        public static void Register(HttpConfiguration config)
        {
            // Create the container as usual.
            Container = new Container();

            Container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

            // Register your types, for instance using the scoped lifestyle:
            Container.RegisterSingleton<IRequestMessageAccessor>(new RequestMessageAccessor(Container));
            Container.Register<Logger.ILogger, Logger.Logger>(Lifestyle.Scoped);

            /// This is an extension method from the integration package.
            Container.RegisterWebApiControllers(GlobalConfiguration.Configuration);
            Container.EnableHttpRequestMessageTracking(GlobalConfiguration.Configuration);

            #if DEBUG
            Container.Verify();
            #endif
            config.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(Container);
            GlobalConfiguration.Configuration.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(Container);
        }
    }

```

This is my controller code, just for demonstration purposes.
```
using System;
using System.Net.Http;
using System.Web.Http;
namespace Api.Controllers.v1
{
    [ApiVersionRoutePrefix("v1", "about")]
    public class AboutController : ApiController
    {
        private readonly IRequestMessageAccessor MyRequest;

        public AboutController(IRequestMessageAccessor MyRequest)
        {
            this.MyRequest = MyRequest;
        }

        [Route("")]
        public IHttpActionResult Get(HttpRequestMessage request)
        {
            try
            {
                // always returns null
                var currentRequest = MyRequest.CurrentMessage;

                return Ok();
            }
            catch (Exception e)
            {
                var exception = (e.InnerException.InnerException != null) ? e.InnerException.InnerException : (e.InnerException != null) ? e.InnerException : e;
                string msg = exception.Message;
                return BadRequest(msg);
            }
        }
    }
}
```

If I understood correctly the **_MyRequest.CurrentMessage_** should return the current request. What am I doing wrong?

**Comment by dotnetjunkie** [comment] 2018-02-06 14:25
Duplicate of https://github.com/simpleinjector/SimpleInjector/issues/511

**Closed by dotnetjunkie** 2018-02-06 14:25 UTC
